### ISSUE TITLE
Fix issue 99 修补完之后nativeInst_riscv32.cpp中的错误

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#103]
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp:233:5: error: 'NativeMovRegMem' has not been declared
233 | int NativeMovRegMem::offset() const {
| ^~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp:233:31: error: non-member function 'int offset()' cannot have cv-qualifier
233 | int NativeMovRegMem::offset() const {
| ^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp:238:6: error: 'NativeMovRegMem' has not been declared
238 | void NativeMovRegMem::set_offset(int x) { Unimplemented(); }
| ^~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp:240:6: error: 'NativeMovRegMem' has not been declared
240 | void NativeMovRegMem::verify() {
| ^~~~~~~~~~~~~~~
make[3]: *** [/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/nativeInst_riscv32.o] Error 1
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/nativeInst_riscv32.o' failed
make[2]: *** [hotspot-core-libs] Error 2
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed

ERROR: Build failed for target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug' (exit code 2)

**Comment by shining1984** [comment]
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:86:14: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
   86 |     assert(h >= 0 && h < _table_size, "Illegal hash value");
      |            ~~^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/debug.hpp:55:9: note: in definition of macro 'vmassert'
   55 |   if (!(p)) {                                                                  \
      |         ^
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:86:5: note: in expansion of macro 'assert'
   86 |     assert(h >= 0 && h < _table_size, "Illegal hash value");
      |     ^~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In member function 'void MacroAssembler::la(Register, u_char* const&)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:725:35: warning: left shift count >= width of type [-Wshift-count-overflow]
  725 |     addi(Rd, Rd, ((int32_t)offset << 52) >> 52);
      |                   ~~~~~~~~~~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:725:42: warning: right shift count >= width of type [-Wshift-count-overflow]
  725 |     addi(Rd, Rd, ((int32_t)offset << 52) >> 52);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In function 'int patch_addr_in_movptr(address, address)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1176:37: warning: left shift count >= width of type [-Wshift-count-overflow]
 1176 |   int32_t lower = ((intptr_t)target << 36) >> 36;
      |                    ~~~~~~~~~~~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1176:44: warning: right shift count >= width of type [-Wshift-count-overflow]
 1176 |   int32_t lower = ((intptr_t)target << 36) >> 36;
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In function 'long int get_offset_of_jal(address)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1205:20: warning: left shift count >= width of type [-Wshift-count-overflow]
 1205 |   offset = (offset << 43) >> 43;
      |             ~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1205:27: warning: right shift count >= width of type [-Wshift-count-overflow]
 1205 |   offset = (offset << 43) >> 43;
      |            ~~~~~~~~~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In function 'long int get_offset_of_conditional_branch(address)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1217:20: warning: left shift count >= width of type [-Wshift-count-overflow]
 1217 |   offset = (offset << 41) >> 41;
      |             ~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1217:27: warning: right shift count >= width of type [-Wshift-count-overflow]
 1217 |   offset = (offset << 41) >> 41;
      |            ~~~~~~~~~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In function 'long int get_offset_of_pc_relative(address)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1226:20: warning: left shift count >= width of type [-Wshift-count-overflow]
 1226 |   offset = (offset << 32) >> 32;
      |             ~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:1226:27: warning: right shift count >= width of type [-Wshift-count-overflow]
 1226 |   offset = (offset << 32) >> 32;
      |            ~~~~~~~~~~~~~~~^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In member function 'void MacroAssembler::la_patchable(Register, const Address&, int32_t&)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:2917:22: warning: integer overflow in expression of type 'long int' results in '-2147483648' [-Woverflow]
 2917 |   if (offset_high >= -((1l << 31)) && offset_low < (1l << 31) + (1l << 12) - 1) {
      |                      ^~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In member function 'void MacroAssembler::inflate_hi32(Register, Register, Register, Register)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:4212:13: warning: overflow in conversion from 'long long int' to 'int32_t' {aka 'int'} changes value from '1095216660480' to '0' [-Woverflow]
 4212 |   li(Rtmp1, 0xFF00000000);
      |             ^~~~~~~~~~~~
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/globalDefinitions.hpp:29,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/align.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/runtime/globals.hpp:29,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/memory/allocation.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/array.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/memory/universe.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/code/oopRecorder.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/codeBuffer.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/assembler.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:31:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp: In instantiation of 'size_t JfrBasicHashtable<T>::hash_to_index(uintptr_t) const [with T = RefCountHandle<RefCountPointer<JfrBlob, MultiThreadedRefCounter> >; size_t = unsigned int; uintptr_t = unsigned int]':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:193:64:   required from 'size_t HashTableHost<T, IdType, Entry, Callback, TABLE_SIZE>::index_for(uintptr_t) [with T = RefCountHandle<RefCountPointer<JfrBlob, MultiThreadedRefCounter> >; IdType = long long unsigned int; Entry = JfrHashtableEntry; Callback = BlobCache; unsigned int TABLE_SIZE = 1009; size_t = unsigned int; uintptr_t = unsigned int]'
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:213:47:   required from 'Entry<T, IdType>* HashTableHost<T, IdType, Entry, Callback, TABLE_SIZE>::lookup_only(uintptr_t) [with T = RefCountHandle<RefCountPointer<JfrBlob, MultiThreadedRefCounter> >; IdType = long long unsigned int; Entry = JfrHashtableEntry; Callback = BlobCache; unsigned int TABLE_SIZE = 1009; uintptr_t = unsigned int]'
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/leakprofiler/checkpoint/objectSampleCheckpoint.cpp:193:73:   required from here
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:86:14: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
   86 |     assert(h >= 0 && h < _table_size, "Illegal hash value");
      |            ~~^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/debug.hpp:55:9: note: in definition of macro 'vmassert'
   55 |   if (!(p)) {                                                                  \
      |         ^
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:86:5: note: in expansion of macro 'assert'
   86 |     assert(h >= 0 && h < _table_size, "Illegal hash value");



* For target hotspot_variant-core_libjvm_objs_os_linux.o:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1356:6: warning: #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time" [-Wcpp]
 1356 |     #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time"
      |      ^~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1859: warning: "RISCV32" redefined
 1859 | #define RISCV32
      | 
<command-line>: note: this is the location of the previous definition
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp: In static member function 'static size_t os::Linux::find_large_page_size()':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:3730:5: error: 'RISCV32_ONLY' was not declared in this scope; did you mean 'PPC32_ONLY'?
 3730 |     RISCV32_ONLY(2 * M);
      |     ^~~~~~~~~~~~
      |     PPC32_ONLY

**Comment by shining1984** [comment]
error: 'RISCV32_ONLY' was not declared in this scope  会在 #104 中进行解决。

**Comment by shining1984** [comment]
编译过程：

bash configure --with-boot-jdk=/home/shining/jdk-10 --openjdk-target=riscv32-unknown-linux-gnu --with-sysroot=/home/shining/riscv32/sysroot --disable-warnings-as-errors --with-debug-level=fastdebug --with-native-debug-symbols=internal --with-jvm-variants=core --prefix=$PWD/fastdebug_32_core

m -j

**Comment by shining1984** [comment]
代码已经提交为 PR #105 中的第一个commit。
请 @DingliZhang 帮忙review和验证。

**Comment by DingliZhang** [comment]
PR #105 已经合并
