### ISSUE TITLE
Fix error: 'RISCV32_ONLY' was not declared in this scope 

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#104]
error: 'RISCV32_ONLY' was not declared in this scope  是在 issue #103 中的问题解决了之后，发现的错误。这个需要解决。

**Comment by shining1984** [comment]
在src/hotspot/share/runtime/vm_version.cpp 中添加了 RISCV32_ONLY相关内容，以及VMTYPE相关内容。
在src/hotspot/share/utilities/macros.hpp中添加了 RISCV32_ONLY相关内容。

**Comment by shining1984** [comment]
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/leakprofiler/checkpoint/objectSampleWriter.cpp:175:113:   required from here
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:86:14: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
   86 |     assert(h >= 0 && h < _table_size, "Illegal hash value");
      |            ~~^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/debug.hpp:55:9: note: in definition of macro 'vmassert'
   55 |   if (!(p)) {                                                                  \
      |         ^
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/jfr/utilities/jfrHashtable.hpp:86:5: note: in expansion of macro 'assert'
   86 |     assert(h >= 0 && h < _table_size, "Illegal hash value");
      |     ^~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp: In static member function 'static jlong OSContainer::read_memory_limit_in_bytes()':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp:482:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
  482 |       char* format = "%s " JULONG_FORMAT;
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp: In static member function 'static jlong OSContainer::memory_and_swap_limit_in_bytes()':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp:505:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
  505 |       char* format = "%s " JULONG_FORMAT;
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1356:6: warning: #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time" [-Wcpp]
 1356 |     #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time"
      |      ^~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1859: warning: "RISCV32" redefined
 1859 | #define RISCV32
      | 
<command-line>: note: this is the location of the previous definition
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os_cpu/linux_riscv32/os_linux_riscv32.cpp: In static member function 'static int64_t os::atomic_load_long_bootstrap(const volatile int64_t*)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os_cpu/linux_riscv32/os_linux_riscv32.cpp:641:1: warning: no return statement in function returning non-void [-Wreturn-type]
  641 | }
      | ^


/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/runtime/sharedRuntimeTrig.cpp: In function 'int __kernel_rem_pio2(double*, double*, int, int, int, const int*)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/runtime/sharedRuntimeTrig.cpp:300:14: warning: 'fq[0]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  300 |     fw = fq[0]-fw;
      |          ~~~~^
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:43:10: fatal error: vmreg_riscv64.inline.hpp: No such file or directory
   43 | #include "vmreg_riscv64.inline.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/sharedRuntime_riscv32.o' failed
make[3]: *** [/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/sharedRuntime_riscv32.o] Error 1
make[2]: *** [hotspot-core-libs] Error 2
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed

**Comment by shining1984** [comment]
sharedRuntime_riscv32.cpp 中修改#include "vmreg_riscv64.inline.hpp" 为#include "vmreg_riscv32.inline.hpp" 。解决#include "vmreg_riscv64.inline.hpp"相关的错误。

**Comment by shining1984** [comment]
Building target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug'
Creating support/modules_libs/java.base/server/libjvm.so from 1 file(s)
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp: In function 'void gen_c2i_adapter(MacroAssembler*, int, int, const BasicType*, const VMRegPair*, Label&)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:432:21: warning: overflow in conversion from 'long long unsigned int' to 'int32_t' {aka 'int'} changes value from '16045762521808612010' to '-559043926' [-Woverflow]
  432 |           __ li(t0, 0xdeadffffdeadaaaaul);
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:451:21: warning: overflow in conversion from 'long long unsigned int' to 'int32_t' {aka 'int'} changes value from '16045762521808612011' to '-559043925' [-Woverflow]
  451 |           __ li(t0, 0xdeadffffdeadaaabul);
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:467:19: warning: overflow in conversion from 'long long unsigned int' to 'int32_t' {aka 'int'} changes value from '16045762521808612012' to '-559043924' [-Woverflow]
  467 |         __ li(t0, 0xdeadffffdeadaaacul);
      |                   ^~~~~~~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp: In static member function 'static void SharedRuntime::gen_i2c_adapter(MacroAssembler*, int, int, const BasicType*, const VMRegPair*)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:565:60: error: no matching function for call to 'MacroAssembler::lw(FloatRegister, Address)'
  565 |         __ lw(r_1->as_FloatRegister(), Address(esp, ld_off));
      |                                                            ^
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/assembler.hpp:454,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:31:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:8: note: candidate: 'void Assembler::lw(Register, Register, int32_t)'
  478 |   INSN(lw,  0b0000011, 0b010);
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:418:8: note: in definition of macro 'INSN'
  418 |   void NAME(Register Rd, Register Rs, const int32_t offset) {                                      \
      |        ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:8: note:   candidate expects 3 arguments, 2 provided
  478 |   INSN(lw,  0b0000011, 0b010);
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:418:8: note: in definition of macro 'INSN'
  418 |   void NAME(Register Rd, Register Rs, const int32_t offset) {                                      \
      |        ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:8: note: candidate: 'void Assembler::lw(Register, address)'
  478 |   INSN(lw,  0b0000011, 0b010);
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:429:8: note: in definition of macro 'INSN'
  429 |   void NAME(Register Rd, address dest) {                                                           \
      |        ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:429:22: note:   no known conversion for argument 1 from 'FloatRegister' {aka 'FloatRegisterImpl*'} to 'Register' {aka 'RegisterImpl*'}
  429 |   void NAME(Register Rd, address dest) {                                                           \
      |             ~~~~~~~~~^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:3: note: in expansion of macro 'INSN'
  478 |   INSN(lw,  0b0000011, 0b010);
      |   ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:8: note: candidate: 'void Assembler::lw(Register, address, relocInfo::relocType)'
  478 |   INSN(lw,  0b0000011, 0b010);
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:410:15: note: in definition of macro 'INSN_ENTRY_RELOC'
  410 |   result_type header {                                                      \
      |               ^~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:3: note: in expansion of macro 'INSN'
  478 |   INSN(lw,  0b0000011, 0b010);
      |   ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:8: note:   candidate expects 3 arguments, 2 provided
  478 |   INSN(lw,  0b0000011, 0b010);
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:410:15: note: in definition of macro 'INSN_ENTRY_RELOC'
  410 |   result_type header {                                                      \
      |               ^~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:3: note: in expansion of macro 'INSN'
  478 |   INSN(lw,  0b0000011, 0b010);
      |   ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:8: note: candidate: 'void Assembler::lw(Register, const Address&, Register)'
  478 |   INSN(lw,  0b0000011, 0b010);
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:444:8: note: in definition of macro 'INSN'
  444 |   void NAME(Register Rd, const Address &adr, Register temp = t0) {                                 \
      |        ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:444:22: note:   no known conversion for argument 1 from 'FloatRegister' {aka 'FloatRegisterImpl*'} to 'Register' {aka 'RegisterImpl*'}
  444 |   void NAME(Register Rd, const Address &adr, Register temp = t0) {                                 \
      |             ~~~~~~~~~^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:3: note: in expansion of macro 'INSN'
  478 |   INSN(lw,  0b0000011, 0b010);
      |   ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:8: note: candidate: 'void Assembler::lw(Register, Label&)'
  478 |   INSN(lw,  0b0000011, 0b010);
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:470:8: note: in definition of macro 'INSN'
  470 |   void NAME(Register Rd, Label &L) {                                                               \
      |        ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:470:22: note:   no known conversion for argument 1 from 'FloatRegister' {aka 'FloatRegisterImpl*'} to 'Register' {aka 'RegisterImpl*'}
  470 |   void NAME(Register Rd, Label &L) {                                                               \
      |             ~~~~~~~~~^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:478:3: note: in expansion of macro 'INSN'
  478 |   INSN(lw,  0b0000011, 0b010);
      |   ^~~~
make[3]: *** [/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/sharedRuntime_riscv32.o] Error 1
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/sharedRuntime_riscv32.o' failed
make[2]: *** [hotspot-core-libs] Error 2
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed

ERROR: Build failed for target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-core_libjvm_objs_sharedRuntime_riscv32.o:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp: In function 'void gen_c2i_adapter(MacroAssembler*, int, int, const BasicType*, const VMRegPair*, Label&)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:432:21: warning: overflow in conversion from 'long long unsigned int' to 'int32_t' {aka 'int'} changes value from '16045762521808612010' to '-559043926' [-Woverflow]
  432 |           __ li(t0, 0xdeadffffdeadaaaaul);
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:451:21: warning: overflow in conversion from 'long long unsigned int' to 'int32_t' {aka 'int'} changes value from '16045762521808612011' to '-559043925' [-Woverflow]
  451 |           __ li(t0, 0xdeadffffdeadaaabul);
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:467:19: warning: overflow in conversion from 'long long unsigned int' to 'int32_t' {aka 'int'} changes value from '16045762521808612012' to '-559043924' [-Woverflow]
  467 |         __ li(t0, 0xdeadffffdeadaaacul);
      |                   ^~~~~~~~~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp: In static member function 'static void SharedRuntime::gen_i2c_adapter(MacroAssembler*, int, int, const BasicType*, const VMRegPair*)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp:565:60: error: no matching function for call to 'MacroAssembler::lw(FloatRegister, Address)'
  565 |         __ lw(r_1->as_FloatRegister(), Address(esp, ld_off));
      |                                                            ^
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/assembler.hpp:454,
   ... (rest of output omitted)

* All command lines available in /home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/make-support/failure-logs.
=== End of repeated output ===

=== Make failed targets repeated here ===
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/sharedRuntime_riscv32.o' failed
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed
=== End of repeated output ===

Hint: Try searching the build log for the name of the first failed target.
Hint: See doc/building.html#troubleshooting for assistance.

/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:300: recipe for target 'main' failed
make[1]: *** [main] Error 2
/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:186: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by shining1984** [comment]
bash configure --with-boot-jdk=/home/shining/jdk-10 --openjdk-target=riscv32-unknown-linux-gnu --with-sysroot=/home/shining/riscv32/sysroot --disable-warnings-as-errors --with-debug-level=fastdebug --with-native-debug-symbols=internal --with-jvm-variants=core --prefix=$PWD/fastdebug_32_core

m -j

**Comment by DingliZhang** [comment]
PR #105 已经合并
