### ISSUE TITLE
Fix the warnings in the hotspot/os/linux

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#112]
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp: In static member function 'static jlong OSContainer::read_memory_limit_in_bytes()':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp:482:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
482 | char* format = "%s " JULONG_FORMAT;
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp: In static member function 'static jlong OSContainer::memory_and_swap_limit_in_bytes()':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp:505:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
505 | char* format = "%s " JULONG_FORMAT;
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1356:6: warning: #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time" [-Wcpp]
1356 | #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time"
| ^~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1859: warning: "RISCV32" redefined
1859 | #define RISCV32
|
:

完整的log在issue #109

**Comment by shining1984** [comment]
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1859: warning: "RISCV32" redefined
1859 | #define RISCV32
|

前期是为了调试方便，现在报警告，就可以直接删除了。

**Comment by shining1984** [comment]
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1356:6: warning: #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time" [-Wcpp]
1356 | #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time"
| ^~~~~~~

这里是代码显示输出warning，不需要修改。

**Comment by shining1984** [comment]
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp: In static member function 'static jlong OSContainer::read_memory_limit_in_bytes()':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp:482:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
482 | char* format = "%s " JULONG_FORMAT;
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp: In static member function 'static jlong OSContainer::memory_and_swap_limit_in_bytes()':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/osContainer_linux.cpp:505:22: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
505 | char* format = "%s " JULONG_FORMAT;


这种warning需要在char* 前加上const。

**Comment by shining1984** [comment]
Building target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug'
Creating support/modules_libs/java.base/server/libjvm.so from 3 file(s)
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp: In member function 'void MacroAssembler::la_patchable(Register, const Address&, int32_t&)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp:2916:22: warning: integer overflow in expression of type 'long int' results in '-2147483648' [-Woverflow]
 2916 |   if (offset_high >= -((1l << 31)) && offset_low < (1l << 31) + (1l << 12) - 1) {
      |                      ^~~~~~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os/linux/os_linux.cpp:1356:6: warning: #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time" [-Wcpp]
 1356 |     #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time"
      |      ^~~~~~~
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: /home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 702f
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 703c
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 7049
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset a1e0
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset a1ed
/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/os_linux_riscv32.o: in function `os::is_first_C_frame(frame*)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os_cpu/linux_riscv32/os_linux_riscv32.cpp:221: multiple definition of `os::is_first_C_frame(frame*)'; /home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef4b
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef57
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef63
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef6f
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 111e7
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 111f5
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 11203
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef7b
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 10c03
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 10c11
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 10c1f
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 10c2d
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 3417a
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 341e9
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 34252
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 342bb
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 34324
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 3438d
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 343f6
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 3445f
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 344c8
/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/os.o:/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/runtime/os.cpp:1190: first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/support/modules_libs/java.base/server/libjvm.so] Error 1
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/support/modules_libs/java.base/server/libjvm.so' failed
make[2]: *** [hotspot-core-libs] Error 2
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed

ERROR: Build failed for target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-core_libjvm_objs_BUILD_LIBJVM_link:
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: /home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 702f
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 703c
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 7049
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset a1e0
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset a1ed
/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/os_linux_riscv32.o: in function `os::is_first_C_frame(frame*)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/os_cpu/linux_riscv32/os_linux_riscv32.cpp:221: multiple definition of `os::is_first_C_frame(frame*)'; /home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef4b
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef57
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef63
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef6f
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 111e7
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 111f5
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 11203
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset ef7b
/home/shining/riscv32/lib/gcc/riscv32-unknown-linux-gnu/10.2.0/../../../../riscv32-unknown-linux-gnu/bin/ld: DWARF error: could not find variable specification at offset 10c03
   ... (rest of output omitted)

* All command lines available in /home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/make-support/failure-logs.
=== End of repeated output ===

=== Make failed targets repeated here ===
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/support/modules_libs/java.base/server/libjvm.so' failed
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed
=== End of repeated output ===

Hint: Try searching the build log for the name of the first failed target.
Hint: See doc/building.html#troubleshooting for assistance.

/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:300: recipe for target 'main' failed
make[1]: *** [main] Error 2
/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:186: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by shining1984** [comment]
@DingliZhang  PR #114 已经发起，请review。

**Comment by DingliZhang** [comment]
已验证并合并
