### ISSUE TITLE
关于使用specjvm2008测试jdk11u性能的问题

### ISSUE THREAD

**Issue by piaoxuebingfeng** [openjdk-riscv/jdk11u#113]
您好！
    请问可以使用specjvm2008 测试 jdk11u 能够得出完整的测试报告么？
    我在openjdk11下测试的时候，在测试compiler.compiler 这一项的时候，报错，如果使用  -coe 参数跳过的话，就拿不到测试的总成绩了，请问这个问题有没有遇到过，该怎样解决?

**Comment by shining1984** [comment]
@DingliZhang 帮忙看下。

**Comment by DingliZhang** [comment]
我们直接忽略掉了compiler.*这两个case，使用官网上的specjvm2008是没办法得出结果的...
