### ISSUE TITLE
关于”入门：使用QEMU用户模式执行Java二进制文件“的踩坑记录

### ISSUE THREAD

**Issue by 13696652781** [openjdk-riscv/jdk11u#141]
基于[https://github.com/openjdk-riscv/jdk11u/wiki/Run-or-debug-with-QEMU-user-mode](url)的入门操作时，应该结合 [https://github.com/openjdk-riscv/jdk11u/wiki/SPECjvm2008-Benchmark](url)一起进行构建。
此处需注意几点：
1、JAVA_HOME针对的是 [https://zhuanlan.zhihu.com/p/344502147](url)提到的JDK11u（nodebug_32/jvm/openjdk-11.0.10-internal）
2、同时基于上述SPECjvm2008操作时，注意jdk对应的依旧是上面jdk117u
![image](https://user-images.githubusercontent.com/42362587/119289208-bc891880-bc7c-11eb-99da-0ad7156d1400.png)
3、在执行脚本包裹时，也要注意它的JAVA_HOME与上述保持一致。执行完之后，如下
![image](https://user-images.githubusercontent.com/42362587/119289389-1b4e9200-bc7d-11eb-83a4-ec4561af88e7.png)
表示包裹成功。
4、尽量直接使用 `/path/to/jdk/java -jar SPECjvm2008.jar -ikv -ict -coe startup.helloworld`这个命令进行测试，不用在“SPECjvm2008”下执行脚本，会报错“Please point the system variable JAVA_HOME to where your jdk is installed.”

**Comment by zhangxiangiscas** [comment]
这里一旦脚本被包裹之后再执行测试命令时，需要修改java-->java-bak，否则会报错“格式不对”
