### ISSUE TITLE
记录一下开发分支的构建过程中遇到的报错以及解决方法

### ISSUE THREAD

**Issue by zhangxiang-plct** [openjdk-riscv/jdk11u#149]

**Comment by zhangxiangiscas** [comment]
但是在SPECjvm2008下可以运行成功

**Comment by zhangxiangiscas** [comment]
构建jdk11的过程中的报错：
`Compiling 8 files for BUILD_TOOLS_LANGTOOLS
warning: [path] bad path element "/path/to/j11/jdk11u/nodebug_32/jvm/openjdk-11.0.12-internal/lib/tools.jar": no such file or directory
warning: [path] bad path element "/lib.dt.jar": no such file or directory
error: warnings found and -Werror specified
Creating support/modules_libs/java.base/server/libjvm.so from 532 file(s)
Creating hotspot/variant-zero/libjvm/gtest/libjvm.so from 86 file(s)
Creating hotspot/variant-zero/libjvm/gtest/gtestLauncher from 1 file(s)
1 error
2 warnings
`

**Comment by zhangxiangiscas** [comment]
今天重新编译了一次，在make clean之后，再次make即可成功

**Comment by zhangxiangiscas** [comment]
core版本的编译已经达到目前进度
![image](https://user-images.githubusercontent.com/84717784/120130677-590d6680-c1f9-11eb-83f9-145cc429662a.png)

**Comment by ZhangXiang1994-max** [comment]
gdb调试时需要注意整个路径的问题，只有出现下述才算通过

`(gdb) set solib-search-path /path/to/dev/jdk11u/nodebug_32/jvm/openjdk-11.0.9-internal/lib:/path/to/dev/jdk11u/nodebug_32/jvm/openjdk-11.0.9-internal/lib/jli:/path/to/dev/jdk11u/nodebug_32/jvm/openjdk-11.0.9-internal/lib/server
Reading symbols from /path/to/dev/jdk11u/nodebug_32/jvm/openjdk-11.0.9-internal/lib/jli/libjli.so...
(No debugging symbols found in /path/to/dev/jdk11u/nodebug_32/jvm/openjdk-11.0.9-internal/lib/jli/libjli.so)
(gdb) i shared
From        To          Syms Read   Shared Object Library
0x3ffe6a00  0x3fff8f5a  Yes         /path/to/riscv32/sysroot/lib/ld-linux-riscv32-ilp32d.so.1
0x3ffca9c0  0x3ffd6be8  Yes         /path/to/riscv32/sysroot/usr/lib/libz.so
0x3ffb70a0  0x3ffc1654  Yes         /path/to/riscv32/sysroot/lib/libpthread.so.0
0x3ffa7e70  0x3ffaec40  Yes (*)     /path/to/dev/jdk11u/nodebug_32/jvm/openjdk-11.0.9-internal/lib/jli/libjli.so
0x3ffa29a0  0x3ffa32ba  Yes         /path/to/riscv32/sysroot/lib/libdl.so.2
0x3fec2ba0  0x3ff6e818  Yes         /path/to/riscv32/sysroot/lib/libc.so.6
(*): Shared library is missing debugging information.
`

**Comment by ZhangXiang1994-max** [comment]
目前进度gdb调试的情况
![Uploading image.png…]()

**Comment by ZhangXiang1994-max** [comment]
二次编译是，删掉了build，重新构建，make clean
还是会出现报错
![image](https://user-images.githubusercontent.com/84717784/120410156-05c81f00-c385-11eb-89ab-0e73fe6890d9.png)

**Comment by ZhangXiang1994-max** [comment]
目前构建进度跟上开发分支的进度：
![Uploading image.png…]()

**Comment by ZhangXiang1994-max** [comment]
目前构建进度跟上开发分支的进度：
![Uploading image.png…]()

**Comment by ZhangXiang1994-max** [comment]
目前gdb调试遇到一个问题：始终无法进入到被断函数
![image](https://user-images.githubusercontent.com/84717784/120573508-493b8f80-c450-11eb-99aa-3b01db64c268.png)

**Comment by ZhangXiang1994-max** [comment]
[Untitled-2.txt](https://github.com/openjdk-riscv/jdk11u/files/6588534/Untitled-2.txt)
具体的操作步骤

**Comment by ZhangXiang1994-max** [comment]
切换至zero版本，仍然没有成功
![image](https://user-images.githubusercontent.com/84717784/120649635-913dcf00-c4af-11eb-89c8-7ce342006b1f.png)

**Comment by ZhangXiang1994-max** [comment]
查明原因：在开始configure的时候参数配置的不对
![image](https://user-images.githubusercontent.com/84717784/120656548-4b383980-c4b6-11eb-819a-daa93ee96813.png)


`bash configure --openjdk-target=riscv32-unknown-linux-gnu --disable-warnings-as-errors --with-sysroot=/path/to/riscv32/sysroot  --with-boot-jdk=/path/to/jdk-10 --with-native-debug-symbols=internal --with-debug-level=slowdebug --with-jvm-variants=core prefix=$PWD/slowdebug_32_core`

**Comment by ZhangXiang1994-max** [comment]
关于openjdk移植的概念问题理解：
首先需要明确交叉编译的概念：在本地机器上进行编译，然后到目标机器去运行程序。
然后我们得明白qemu的作用，qemu是一个模拟器，可以模拟不同的处理器去执行程序。或者说它的用户模式能启动那些为不同中央处理器编译的Linux程序。
我们在x86的主机上编译openjdk，然后利用qemu的riscv32/64的用户模式去启动它，当出现能够出现“hello world”即意味移植成功。
JDK的主要构成包括了Jre+jvm.java的跨平台特性主要是依赖于jvm与操作系统直接交互，而不是直接编译成机器语言与目标机器交互。原来的openjdk中源码中Hotspot部分下有支持x86、linux_arm、windows等等各种操作系统的代码，所以具体到移植工作就是：我们需要在openjdk中关于jvm的部分增加支持与RISCV32/64指令的代码，也就是通过jvm支持与各种操作系统直接交互。实现了移植。
