### ISSUE TITLE
开发分支gdb调试的问题记录

### ISSUE THREAD

**Issue by zhangxiang-plct** [openjdk-riscv/jdk11u#154]
第一种情况，采用配置：
`bash configure --openjdk-target=riscv32-unknown-linux-gnu --disable-warnings-as-errors --with-sysroot=/path/to/riscv32/sysroot --x-includes=/path/to/riscv32/sysroot/usr/include --x-libraries=/path/to/riscv32/sysroot/usr/lib --with-boot-jdk=/path/to/jdk-10 --with-native-debug-symbols=none --with-jvm-variants=zero --with-jvm-interpreter=cpp --prefix=$PWD/nodebug_32`
gdb的调试过程无法进行下去
![image](https://user-images.githubusercontent.com/84717784/120729840-bf082f80-c512-11eb-844e-f951e32f9075.png)

**Comment by ZhangXiang1994-max** [comment]
第二种情况：`bash configure --openjdk-target=riscv32-unknown-linux-gnu --disable-warnings-as-errors --with-sysroot=/path/to/riscv32/sysroot --x-includes=/path/to/riscv32/sysroot/usr/include --x-libraries=/path/to/riscv32/sysroot/usr/lib --with-boot-jdk=/path/to/jdk-10 --with-native-debug-symbols=internal --with-debug-level=fastdebug --with-jvm-variants=core --prefix=$PWD/fastdebug_32_core`
b b macroAssembler_riscv32.cpp:2632,能正常进入被断函数
![image](https://user-images.githubusercontent.com/84717784/120732419-db5a9b00-c517-11eb-9b8b-c235bb6b7508.png)
但是，b bytecode.hpp:327，无法进入
![image](https://user-images.githubusercontent.com/84717784/120732491-fc22f080-c517-11eb-89cd-7873adecd951.png)

**Comment by ZhangXiang1994-max** [comment]
`第三种情况：
`bash configure --openjdk-target=riscv32-unknown-linux-gnu --disable-warnings-as-errors --with-sysroot=/path/to/riscv32/sysroot --with-boot-jdk=/path/to/jdk-10 --with-native-debug-symbols=internal --with-debug-level=slowdebug --with-jvm-variants=core prefix=$PWD/slowdebug_32_core`
能够正常调试：
![image](https://user-images.githubusercontent.com/84717784/120734294-3772ee80-c51b-11eb-8006-bb75b6a26fdf.png)

**Comment by ZhangXiang1994-max** [comment]
总结：gdb调试只适合用slowdebug版本进行调试，其余版本不建议，报错点函数gdb无法跟进

**Comment by ZhangXiang1994-max** [comment]
调试jvm的启动函数时，输入“adv 296”
![image](https://user-images.githubusercontent.com/84717784/121334710-7c988580-c94c-11eb-906d-467f22f3828d.png)
然而第二次我手动单步跟踪时，没有报错

**Comment by ZhangXiang1994-max** [comment]
采用最新的dev分支跟踪调试[java -version调试记录](https://github.com/openjdk-riscv/jdk11u/issues/126)
![image](https://user-images.githubusercontent.com/84717784/124435662-c9cf1200-dda7-11eb-80bc-122ee1f60259.png)

**Comment by ZhangXiang1994-max** [comment]
断在了  InterpreterRuntime::resolve_ldc (thread=0x3ed19000, bytecode=Bytecodes::_ldc) at /path/to/dev/jdk11u/src/hotspot/share/interpreter/interpreterRuntime.cpp:187

![image](https://user-images.githubusercontent.com/84717784/124439507-16b4e780-ddac-11eb-819f-b1ba6494118e.png)

**Comment by ZhangXiang1994-max** [comment]
以毕昇jdk为例，注释掉了“bishengjdk-11/src/hotspot/cpu/riscv64/templateTable_riscv64.cpp”中的condy_helper函数关于ldc的调用
，重新编译，没有报错
![image](https://user-images.githubusercontent.com/84717784/124845603-a683ad00-dfc9-11eb-9155-a559888371cb.png)

**Comment by DingliZhang** [comment]
以毕昇jdk为例，根据 [issue126](https://github.com/openjdk-riscv/jdk11u/issues/126#issuecomment-872700651) 注释掉了TemplateTable::ldc函数体，并在`src/hotspot/share/interpreter/interpreterRuntime.cpp`中的`Bytecode_loadconstant ldc(m, last_frame.bci());`执行之前打上了`warning: new ldc...`标记，结果如下：
![image](https://user-images.githubusercontent.com/19571377/124848161-d97c6f80-dfce-11eb-9da1-1ff1006a6bdb.png)

**Comment by ZhangXiang1994-max** [comment]
以开发分支的rv32为例，注释了\dev\jdk11u\src\hotspot\cpu\riscv32\templateTable_riscv32.cpp中TemplateTable::ldc关于condy_helper的调用.
报错如下：
![image](https://user-images.githubusercontent.com/84717784/125019647-fe91e080-e0a9-11eb-916b-eb3fdd76b044.png)

**Comment by ZhangXiang1994-max** [comment]
以开发分支的rv32为例，根据 issue126 注释掉了TemplateTable::ldc函数体
报错情况同上个comment一致，上一个是在该函数内注释了condy_helper的调用。而在毕昇jdk中注释这个函数体，得到的报错不一样，推测主要出错还是在condy_helper的函数上

**Comment by ZhangXiang1994-max** [comment]
只单独注释condy_helper的_call_vm，会报：
![Uploading image.png…]()

**Comment by ZhangXiang1994-max** [comment]
对bishengjdk跟开发分支的rv32g在TemplateTable::ldc函数处进行断点调试，发现都能正常进入condy_helper，再观察condy_helper
![image](https://user-images.githubusercontent.com/84717784/125469459-40e96a9f-5c20-4474-aca1-16091ccc7544.png)
在switch时，选择的都是18，并且正常走完分支。

**Comment by ZhangXiang1994-max** [comment]
参考 @DingliZhang 的调试方法
![image](https://user-images.githubusercontent.com/84717784/125474782-210f20e9-ca84-4440-8568-9c84468447fb.png)
在这两处加上打印
获得结果如下
![image](https://user-images.githubusercontent.com/84717784/125474880-d9673ab5-9c8c-4cfd-95dd-dd038d6984b7.png)
此调试以毕昇64为例

**Comment by ZhangXiang1994-max** [comment]
目前能看到的指令230对应的是_fast_aldc这个指令，上网查了一下，是ldc的重写形式，为什么会出现这个指令，似乎涉及到“初始化类后,HotSpot会使用JVM特定的 fast_aldc 字节码重写 ldc 字节码,以引用常量池中的字符串条目”。  @DingliZhang

**Comment by ZhangXiang1994-max** [comment]
7.18更新：
以当前的patch编译之后，在gdb调试时，第120次时出现段错误
![image](https://user-images.githubusercontent.com/84717784/126071844-2fe8e626-787c-4cc8-9978-278ba01a9a57.png)
