### ISSUE TITLE
编译过程中的warning整理

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#164]
编译的原始记录：[make.log](https://github.com/openjdk-riscv/jdk11u/files/6951985/make.log) 
pastebin：https://paste.ubuntu.com/p/HcKj6wx9rp/

**Comment by DingliZhang** [comment]
主要warning分类：
### comparison of unsigned expression in 'xxx' is always true [-Wtype-limits]
```
src/hotspot/share/jfr/utilities/jfrHashtable.hpp:86:14: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
   86 |     assert(h >= 0 && h < _table_size, "Illegal hash value");
      |            ~~^~~~
```
```
src/hotspot/share/jfr/utilities/jfrDoublyLinkedList.hpp:138:17: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
  138 |   assert(_count >= 0, "invariant");
```

### #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time" [-Wcpp]
```
src/hotspot/os/linux/os_linux.cpp:1356:6: warning: #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time" [-Wcpp]
 1356 |     #warning "SYS_clock_getres not defined for this platform, disabling fast_thread_cpu_time"
      |      ^~~~~~~
```

### no return statement in function returning non-void [-Wreturn-type]
```
src/hotspot/os_cpu/linux_riscv32/atomic_linux_riscv32.hpp:115:76: warning: no return statement in function returning non-void [-Wreturn-type]
  115 | inline T Atomic::PlatformLoad<8>::operator()(T const volatile* src) const {}
      |                                                                            ^
```

### cast between incompatible function types from 'xxx' to 'xxx' [-Wcast-function-type]
```
src/java.base/unix/native/libjli/java_md_solinux.c:748:37: warning: cast between incompatible function types from 'int (*)(void *)' to 'void * (*)(void *)' [-Wcast-function-type]
  748 |     if (pthread_create(&tid, &attr, (void *(*)(void*))continuation, (void*)args) == 0) {
      | 
```

###  'xxx' clearing an object of non-trivial type 'xxx'; use assignment or value-initialization instead [-Wclass-memaccess]
```
src/java.desktop/share/native/libfontmanager/harfbuzz/hb-aat-map.hh:41:36: warning: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct hb_aat_map_t'; use assignment or value-initialization instead [-Wclass-memaccess]
   41 |     memset (this, 0, sizeof (*this));
      |                            
```

###  'xxx' writing to an object of type 'xxx' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
```
src/java.desktop/share/native/libfontmanager/harfbuzz/hb-null.hh:160:10: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct CFF::byte_str_t' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  160 |   memcpy (obj, &Null(Type), sizeof (*obj));
      |   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### 'xxx' moving an object of non-trivially copyable type 'xxx'; use 'new' and 'delete' instead [-Wclass-memaccess]
```
src/java.desktop/share/native/libfontmanager/harfbuzz/hb-vector.hh:164:36: warning: 'void* realloc(void*, size_t)' moving an object of non-trivially copyable type 'struct CFF::cff1_private_dict_values_base_t<CFF::op_str_t>'; use 'new' and 'delete' instead [-Wclass-memaccess]
  164 |       new_array = (Type *) realloc (arrayZ_, new_allocated * sizeof (Type));
      |                            ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by DingliZhang** [comment]
## comparison of unsigned expression in 'xxx' is always true [-Wtype-limits]
`h`及`count`数据类型都为`size_t`，则`h`及`count`为无符号整型，恒大于零。
已提交PR #165 ，编译过程中相关warning已不再出现，jdk运行结果没有变化，请 @shining1984 review并验证。

**Comment by shining1984** [comment]
http://paste.ubuntu.com/p/cbRCfm8fpq/

**Comment by DingliZhang** [comment]
### [-Wclass-memaccess]
这类主要是 GCC 8+版本会在使用memcpy/memcpy 等操作类指针 ( -Wclass-memaccess)弹出warning，可以通过将目标指针强制转换为void*来避免警告。
已提交PR #166

**Comment by ZhangXiang1994-max** [comment]
关于“【-Wcpp】”告警处理：
在毕昇jdk中加log
![Uploading image.png…]()
发现最后的编译过程中，都没有出现“#warning”的相关打印，意味着“SYS_clock_getres”是被定义的。
而在rv32的开发分支中，出现了“#warning”的相关打印，产生了矛盾。
尚未解决。

------------

关于“src/hotspot/os_cpu/linux_riscv32/atomic_linux_riscv32.hpp:115:76: warning: no return statement in function returning non-void [-Wreturn-type]
  115 | inline T Atomic::PlatformLoad<8>::operator()(T const volatile* src) const {}
      |                                                                            ^
”的告警处理：
了解到该指令暂时还未写，所以处理它的意义暂时不大，可以暂时不用考虑修改。

**Comment by DingliZhang** [comment]
### [-Wcast-function-type]
解决的时候参考了 https://github.com/openjdk/jdk11u/commit/3870110348231252be1d53d24979a8b585f5dd84
已提交PR #167

**Comment by DingliZhang** [comment]
### [-Wcpp]
在kernel
`SYS_clock_getres`是在工具链`riscv32/sysroot/usr/include/bits/syscall.h`中定义的:
```
#ifdef __NR_clock_getres
# define SYS_clock_getres __NR_clock_getres
#endif
```
而`__NR_clock_getres`是在工具链`riscv32/sysroot/usr/include/asm-generic/unistd.h`中定义的
```
#if defined(__ARCH_WANT_TIME32_SYSCALLS) || __BITS_PER_LONG != 32
#define __NR_clock_settime 112
__SC_3264(__NR_clock_settime, sys_clock_settime32, sys_clock_settime)
#define __NR_clock_gettime 113
__SC_3264(__NR_clock_gettime, sys_clock_gettime32, sys_clock_gettime)
#define __NR_clock_getres 114
__SC_3264(__NR_clock_getres, sys_clock_getres_time32, sys_clock_getres)
#define __NR_clock_nanosleep 115
__SC_3264(__NR_clock_nanosleep, sys_clock_nanosleep_time32, \
	  sys_clock_nanosleep)
#endif
```
在[Make time32 syscall numbers optional](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/include/uapi/asm-generic/unistd.h?h=v5.10.57&id=c8ce48f06503eee20f189eed5b2aa736272b7344)中，由于我们希望新架构提供旧的 32 位基于 time_t 的系统调用或定义系统调用号宏，因此添加一个新的 __ARCH_WANT_TIME32_SYSCALLS宏，这个宏通常在`linux/arch/<arch_name>/include/uapi/asm/unistd.h`中定义，而`linux/arch/riscv/include/uapi/asm/unistd.h`中没有对这个宏做定义；
除此之外，对于riscv32来说，`__BITS_PER_LONG`会被拓展为4 * 8，因此`defined(__ARCH_WANT_TIME32_SYSCALLS) || __BITS_PER_LONG != 32`为false，导致warning出现。
