### ISSUE TITLE
商讨完成Hotspot解释器部分的代码移植模块分割和顺序

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#17]
将Hotspot解释器部分的代码进行分割，分成模块逐步进行移植。

需要确定模块的分割边界以及移植的顺序。

@shining1984 和 @DingliZhang 商讨确定最终版本，更新到 https://github.com/openjdk-riscv/jdk11u/wiki/Project-Roadmap 中。

**Comment by shining1984** [comment]
该issue目的是为后续移植解释器做方向性的指导，分模块移植是为了在移植过程中更好的确认代码中的问题，避免一堆代码一下子堆到一起无法定位问题。

**Comment by shining1984** [comment]
版本V0.5  （不包含 汇编器、宏汇编器、反汇编器、C1、C2、GC，这些内容是单独其他块内容做）

抽象解释器、模版解释器的相关内容
1）src/hotspot/cpu/riscv32/abstractInterpreter_riscv32.cpp
2）src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
3)  src/hotspot/cpu/riscv32/interp_masm_riscv32.hpp
4)  src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp
5)  src/hotspot/cpu/riscv32/interpreterRT_riscv32.hpp
6)  src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
7) src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
8) src/hotspot/cpu/riscv32/templateTable_riscv32.hpp


frame相关内容
1) src/hotspot/cpu/riscv32/frame_riscv32.cpp
2) src/hotspot/cpu/riscv32/frame_riscv32.hpp
3) src/hotspot/cpu/riscv32/frame_riscv32.inline.hpp
4) src/hotspot/cpu/riscv32/javaFrameAnchor_riscv32.hpp

global相关
1) src/hotspot/cpu/riscv32/globalDefinitions_riscv32.hpp
2) src/hotspot/cpu/riscv32/globals_riscv32.hpp

cache相关
1) src/hotspot/cpu/riscv32/icache_riscv32.cpp
2) src/hotspot/cpu/riscv32/icache_riscv32.hpp
3) 

jni相关
1) src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp
2) src/hotspot/cpu/riscv32/jniTypes_riscv32.cpp

methodHandle相关
1) src/hotspot/cpu/riscv32/methodHandles_riscv32.cpp
2) src/hotspot/cpu/riscv32/methodHandles_riscv32.hpp

nativeInst相关
1) src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
2) src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

register相关
1) src/hotspot/cpu/riscv32/registerMap_riscv32.hpp
2) src/hotspot/cpu/riscv32/register_defitions_riscv32.cpp
3) src/hotspot/cpu/riscv32/register_riscv32.cpp
4) src/hotspot/cpu/riscv32/register_riscv32.hpp

reloc相关
1) src/hotspot/cpu/riscv32/relocInfo_riscv32.cpp
2) src/hotspot/cpu/riscv32/relocInfo_riscv32.hpp

stub相关
1) src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
2) src/hotspot/cpu/riscv32/stubRoutines_riscv32.cpp
3) src/hotspot/cpu/riscv32/stubRoutines_riscv32.hpp
4) src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp

vm相关
1) src/hotspot/cpu/riscv32/vmStructs_riscv32.hpp
2) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.cpp
3) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.hpp
4)  src/hotspot/cpu/riscv32/vm_version_riscv32.cpp
5)  src/hotspot/cpu/riscv32/vm_version_riscv32.hpp
6)  src/hotspot/cpu/riscv32/vmreg_riscv32.cpp
7)  src/hotspot/cpu/riscv32/vmreg_riscv32.hpp
8)  src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp

其他：
1) src/hotspot/cpu/riscv32/bytes_riscv32.hpp
2) src/hotspot/cpu/riscv32/codeBuffer_riscv32.hpp
3) src/hotspot/cpu/riscv32/compiledIC_riscv32.cpp
4) src/hotspot/cpu/riscv32/copy_riscv32.cpp
5) src/hotspot/cpu/riscv32/depChecker_riscv32.hpp
6) src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp
7) src/hotspot/cpu/riscv32/riscv32-asmtest.py
8) src/hotspot/cpu/riscv32/riscv32.ad
9) src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

-----------------------------
这只是初步的划分模块办法，为了方便移植，移植过程中可以进一步细分，或者进行微调。
@DingliZhang ，请review看看有没有进一步的意见。

**Comment by DingliZhang** [comment]
非常清楚，没有问题。
在编译的时候可能需要同时修改几个有关联的不同模块的文件，我们可以根据编译给出的调试信息具体分析，之后再来同步。
@shining1984

**Comment by shining1984** [comment]
> 非常清楚，没有问题。
> 在编译的时候可能需要同时修改几个有关联的不同模块的文件，我们可以根据编译给出的调试信息具体分析，之后再来同步。
> @shining1984

嗯，是的。这些模块并不一定按照先后顺序来，可以打乱顺序根据需要移植。划分是为了每次提交的patch尽量小一些，这样方便review和后续复查代码。我可能会再做些微调。

**Comment by shining1984** [comment]
版本V0.6 （不包含 汇编器、宏汇编器、反汇编器、C1、C2、GC，这些内容是单独其他块内容做）

抽象解释器、模版解释器的相关内容
1）src/hotspot/cpu/riscv32/abstractInterpreter_riscv32.cpp
2)  src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp

masm相关：
1）src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
2)  src/hotspot/cpu/riscv32/interp_masm_riscv32.hpp

interpreterRT相关
1)  src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp
2)  src/hotspot/cpu/riscv32/interpreterRT_riscv32.hpp

templateTable相关内容
1) src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
2) src/hotspot/cpu/riscv32/templateTable_riscv32.hpp

frame相关内容
1) src/hotspot/cpu/riscv32/frame_riscv32.cpp
2) src/hotspot/cpu/riscv32/frame_riscv32.hpp
3) src/hotspot/cpu/riscv32/frame_riscv32.inline.hpp
4) src/hotspot/cpu/riscv32/javaFrameAnchor_riscv32.hpp

global相关
1) src/hotspot/cpu/riscv32/globalDefinitions_riscv32.hpp
2) src/hotspot/cpu/riscv32/globals_riscv32.hpp

cache相关
1) src/hotspot/cpu/riscv32/icache_riscv32.cpp
2) src/hotspot/cpu/riscv32/icache_riscv32.hpp

jni相关
1) src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp
2) src/hotspot/cpu/riscv32/jniTypes_riscv32.cpp

methodHandle相关
1) src/hotspot/cpu/riscv32/methodHandles_riscv32.cpp
2) src/hotspot/cpu/riscv32/methodHandles_riscv32.hpp

nativeInst相关
1) src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
2) src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

register相关
1) src/hotspot/cpu/riscv32/registerMap_riscv32.hpp
2) src/hotspot/cpu/riscv32/register_defitions_riscv32.cpp
3) src/hotspot/cpu/riscv32/register_riscv32.cpp
4) src/hotspot/cpu/riscv32/register_riscv32.hpp

reloc相关
1) src/hotspot/cpu/riscv32/relocInfo_riscv32.cpp
2) src/hotspot/cpu/riscv32/relocInfo_riscv32.hpp

stub相关
1) src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
2) src/hotspot/cpu/riscv32/stubRoutines_riscv32.cpp
3) src/hotspot/cpu/riscv32/stubRoutines_riscv32.hpp
4) src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp

vm版本相关
1) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.cpp
2) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.hpp
3)  src/hotspot/cpu/riscv32/vm_version_riscv32.cpp
4)  src/hotspot/cpu/riscv32/vm_version_riscv32.hpp


vm结构体和寄存器相关
1) src/hotspot/cpu/riscv32/vmStructs_riscv32.hpp
2)  src/hotspot/cpu/riscv32/vmreg_riscv32.cpp
3)  src/hotspot/cpu/riscv32/vmreg_riscv32.hpp
4)  src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp

脚本相关：
1) src/hotspot/cpu/riscv32/riscv32-asmtest.py
2) src/hotspot/cpu/riscv32/riscv32.ad

其他：
1) src/hotspot/cpu/riscv32/bytes_riscv32.hpp
2) src/hotspot/cpu/riscv32/codeBuffer_riscv32.hpp
3) src/hotspot/cpu/riscv32/compiledIC_riscv32.cpp
4) src/hotspot/cpu/riscv32/copy_riscv32.cpp
5) src/hotspot/cpu/riscv32/depChecker_riscv32.hpp
6) src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp
7) src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

**Comment by shining1984** [comment]
汇编器相关内容
1) src/hotspot/cpu/riscv32/assembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/assembler_riscv32.hpp
3) src/hotspot/cpu/riscv32/assembler_riscv32.inline.hpp

反汇编器相关内容
1) src/hotspot/cpu/riscv32/disassembler_riscv32.hpp

宏汇编器相关内容
1) src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
3) src/hotspot/cpu/riscv32/macroAssembler_riscv32.inline.hpp

**Comment by shining1984** [comment]
版本V0.7（不包含C1、C2、GC，这些内容是单独其他块内容做）

抽象解释器、模版解释器的相关内容
1) src/hotspot/cpu/riscv32/abstractInterpreter_riscv32.cpp
2) src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp

masm相关：
1) src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
2) src/hotspot/cpu/riscv32/interp_masm_riscv32.hpp

interpreterRT相关
1) src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp
2) src/hotspot/cpu/riscv32/interpreterRT_riscv32.hpp

templateTable相关内容
1) src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
2) src/hotspot/cpu/riscv32/templateTable_riscv32.hpp

frame相关内容
1) src/hotspot/cpu/riscv32/frame_riscv32.cpp
2) src/hotspot/cpu/riscv32/frame_riscv32.hpp
3) src/hotspot/cpu/riscv32/frame_riscv32.inline.hpp
4) src/hotspot/cpu/riscv32/javaFrameAnchor_riscv32.hpp

global相关
1) src/hotspot/cpu/riscv32/globalDefinitions_riscv32.hpp
2) src/hotspot/cpu/riscv32/globals_riscv32.hpp

cache相关
1) src/hotspot/cpu/riscv32/icache_riscv32.cpp
2) src/hotspot/cpu/riscv32/icache_riscv32.hpp

jni相关
1) src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp
2) src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp

methodHandle相关
1) src/hotspot/cpu/riscv32/methodHandles_riscv32.cpp
2) src/hotspot/cpu/riscv32/methodHandles_riscv32.hpp

nativeInst相关
1) src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
2) src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

register相关
1) src/hotspot/cpu/riscv32/registerMap_riscv32.hpp
2) src/hotspot/cpu/riscv32/register_defitions_riscv32.cpp
3) src/hotspot/cpu/riscv32/register_riscv32.cpp
4) src/hotspot/cpu/riscv32/register_riscv32.hpp

reloc相关
1) src/hotspot/cpu/riscv32/relocInfo_riscv32.cpp
2) src/hotspot/cpu/riscv32/relocInfo_riscv32.hpp

stub相关
1) src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
2) src/hotspot/cpu/riscv32/stubRoutines_riscv32.cpp
3) src/hotspot/cpu/riscv32/stubRoutines_riscv32.hpp
4) src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp

vm版本相关
1) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.cpp
2) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.hpp
3)  src/hotspot/cpu/riscv32/vm_version_riscv32.cpp
4)  src/hotspot/cpu/riscv32/vm_version_riscv32.hpp


vm结构体和寄存器相关
1) src/hotspot/cpu/riscv32/vmStructs_riscv32.hpp
2)  src/hotspot/cpu/riscv32/vmreg_riscv32.cpp
3)  src/hotspot/cpu/riscv32/vmreg_riscv32.hpp
4)  src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp

脚本相关：
1) src/hotspot/cpu/riscv32/riscv32-asmtest.py
2) src/hotspot/cpu/riscv32/riscv32.ad

其他：
1) src/hotspot/cpu/riscv32/bytes_riscv32.hpp
2) src/hotspot/cpu/riscv32/codeBuffer_riscv32.hpp
3) src/hotspot/cpu/riscv32/compiledIC_riscv32.cpp
4) src/hotspot/cpu/riscv32/copy_riscv32.cpp
5) src/hotspot/cpu/riscv32/depChecker_riscv32.hpp
6) src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp
7) src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

汇编器相关内容
1) src/hotspot/cpu/riscv32/assembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/assembler_riscv32.hpp
3) src/hotspot/cpu/riscv32/assembler_riscv32.inline.hpp

反汇编器相关内容
1) src/hotspot/cpu/riscv32/disassembler_riscv32.hpp

宏汇编器相关内容
1) src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
3) src/hotspot/cpu/riscv32/macroAssembler_riscv32.inline.hpp

**Comment by DingliZhang** [comment]
> 其他中 4.src/hotspot/cpu/riscv32/copy_riscv32.cpp
此处有笔误，应为copy_riscv32.hpp

**Comment by shining1984** [comment]
> > 其他中 4.src/hotspot/cpu/riscv32/copy_riscv32.cpp
> 
> 此处有笔误，应为copy_riscv32.hpp

已经更新。

**Comment by shining1984** [comment]
版本V0.8（不包含C1、C2）

抽象解释器、模版解释器的相关内容
1) src/hotspot/cpu/riscv32/abstractInterpreter_riscv32.cpp
2) src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp

masm相关：
1) src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp
2) src/hotspot/cpu/riscv32/interp_masm_riscv32.hpp

interpreterRT相关
1) src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp
2) src/hotspot/cpu/riscv32/interpreterRT_riscv32.hpp

templateTable相关内容
1) src/hotspot/cpu/riscv32/templateTable_riscv32.cpp
2) src/hotspot/cpu/riscv32/templateTable_riscv32.hpp

frame相关内容
1) src/hotspot/cpu/riscv32/frame_riscv32.cpp
2) src/hotspot/cpu/riscv32/frame_riscv32.hpp
3) src/hotspot/cpu/riscv32/frame_riscv32.inline.hpp
4) src/hotspot/cpu/riscv32/javaFrameAnchor_riscv32.hpp

global相关
1) src/hotspot/cpu/riscv32/globalDefinitions_riscv32.hpp
2) src/hotspot/cpu/riscv32/globals_riscv32.hpp

cache相关
1) src/hotspot/cpu/riscv32/icache_riscv32.cpp
2) src/hotspot/cpu/riscv32/icache_riscv32.hpp

jni相关
1) src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp
2) src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp

methodHandle相关
1) src/hotspot/cpu/riscv32/methodHandles_riscv32.cpp
2) src/hotspot/cpu/riscv32/methodHandles_riscv32.hpp

nativeInst相关
1) src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
2) src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

register相关
1) src/hotspot/cpu/riscv32/registerMap_riscv32.hpp
2) src/hotspot/cpu/riscv32/register_defitions_riscv32.cpp
3) src/hotspot/cpu/riscv32/register_riscv32.cpp
4) src/hotspot/cpu/riscv32/register_riscv32.hpp

reloc相关
1) src/hotspot/cpu/riscv32/relocInfo_riscv32.cpp
2) src/hotspot/cpu/riscv32/relocInfo_riscv32.hpp

stub相关
1) src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
2) src/hotspot/cpu/riscv32/stubRoutines_riscv32.cpp
3) src/hotspot/cpu/riscv32/stubRoutines_riscv32.hpp
4) src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp

vm版本相关
1) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.cpp
2) src/hotspot/cpu/riscv32/vm_version_ext_riscv32.hpp
3)  src/hotspot/cpu/riscv32/vm_version_riscv32.cpp
4)  src/hotspot/cpu/riscv32/vm_version_riscv32.hpp


vm结构体和寄存器相关
1) src/hotspot/cpu/riscv32/vmStructs_riscv32.hpp
2)  src/hotspot/cpu/riscv32/vmreg_riscv32.cpp
3)  src/hotspot/cpu/riscv32/vmreg_riscv32.hpp
4)  src/hotspot/cpu/riscv32/vmreg_riscv32.inline.hpp

脚本相关：
1) src/hotspot/cpu/riscv32/riscv32-asmtest.py
2) src/hotspot/cpu/riscv32/riscv32.ad

其他：
1) src/hotspot/cpu/riscv32/bytes_riscv32.hpp
2) src/hotspot/cpu/riscv32/codeBuffer_riscv32.hpp
3) src/hotspot/cpu/riscv32/compiledIC_riscv32.cpp
4) src/hotspot/cpu/riscv32/copy_riscv32.hpp
5) src/hotspot/cpu/riscv32/depChecker_riscv32.hpp
6) src/hotspot/cpu/riscv32/icBuffer_riscv32.cpp
7) src/hotspot/cpu/riscv32/sharedRuntime_riscv32.cpp

汇编器相关内容
1) src/hotspot/cpu/riscv32/assembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/assembler_riscv32.hpp
3) src/hotspot/cpu/riscv32/assembler_riscv32.inline.hpp

反汇编器相关内容
1) src/hotspot/cpu/riscv32/disassembler_riscv32.hpp

宏汇编器相关内容
1) src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
3) src/hotspot/cpu/riscv32/macroAssembler_riscv32.inline.hpp

GC相关内容1
1) src/hotspot/cpu/riscv32/gc/g1/g1BarrierSetAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/gc/g1/g1BarrierSetAssembler_riscv32.hpp

GC相关内容2
1) src/hotspot/cpu/riscv32/gc/shared/barrierSetAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/gc/shared/barrierSetAssembler_riscv32.hpp

GC相关内容3
1) src/hotspot/cpu/riscv32/gc/shared/cardTableBarrierSetAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/gc/shared/cardTableBarrierSetAssembler_riscv32.hpp

GC相关内容4
1) src/hotspot/cpu/riscv32/gc/shared/modRefBarrierSetAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/gc/shared/modRefBarrierSetAssembler_riscv32.hpp

GC相关内容5
1) src/hotspot/cpu/riscv32/gc/shenandoah/c1/shenandoahBarrierSetC1_riscv32.cpp

GC相关内容6
1) src/hotspot/cpu/riscv32/gc/shenandoah/shenandoahBarrierSetAssembler_riscv32.cpp
2) src/hotspot/cpu/riscv32/gc/shenandoah/shenandoahBarrierSetAssembler_riscv32.hpp
3) src/hotspot/cpu/riscv32/gc/shenandoah_riscv32.ad

**Comment by shining1984** [comment]
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/runtime/riscv32
RISCV32CurrentFrameGuess.java
RISCV32Frame.java
RISCV32JavaCallWrapper.java
RISCV32RegisterMap.java

**Comment by shining1984** [comment]
非src/hotspot目录添加文件2：

src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/riscv32/RISCV32ThreadContext.java

src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/riscv32/ProcRISCV32Thread.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/riscv32/ProcRISCV32ThreadContext.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/riscv32/ProcRISCV32ThreadFactory.java

src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/remote/riscv32/RemoteRISCV32Thread.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/remote/riscv32/RemoteRISCV32ThreadContext.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/remote/riscv32/RemoteRISCV32ThreadFactory.java

src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/linux/riscv32/LinuxRISCV32CFrame.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/linux/riscv32/LinuxRISCV32ThreadContext.java

src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/proc/ProcDebuggerLocal.java
src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/linux/LinuxcDebugger.java

src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/debugger/MachineDescriptionRiscv32.java

此外，还修改了一些文件，具体见 issue #123.
