### ISSUE TITLE
如何使用IDE进行调试

### ISSUE THREAD

**Issue by zifeihan** [openjdk-riscv/jdk11u#174]
目标: 目前使用gdb调试,稍微麻烦了一些. 如何使用IDE（clion,vscode,netbeans等）进行跨平台调试,主要涉及在IDE机器上是否存在相应版本的gdb, 远程机器上使用的是rv32版本的gdb启动, 如果两端版本不一致,数据通信协议解析不了（已测试）.
目前进展: 目前调试断点可以打上去, 但是符号表有点对应不上, 正在解决中.

**Comment by zifeihan** [comment]
目前进展,可以在linux vscode进行调试. 效果如下:
![image](https://user-images.githubusercontent.com/16839929/132441814-b3d87b02-11aa-4a05-8a27-5f587107dafd.png)

**Comment by DingliZhang** [comment]
Hi @zifeihan 
我之前也做过vscode上gdb的调试的尝试，在`jdk11u`目录下生成`launch.json`，内容为：
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/bin/java",
            "args": [
                "-version"],
            "stopAtEntry": false,
            "cwd": "<path-to-jdk-src>",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "<path-to-toolchain-riscv32>/bin/riscv32-unknown-linux-gnu-gdb",
            "miDebuggerServerAddress": "localhost:<port>",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true,
                }
            ]
        }
    ]
}
```
主要修改的配置有：
"program"、"args"、"miDebuggerPath"、"miDebuggerServerAddress"

之后在终端中使用命令行启动`qemu java -version`：
```
/home/dingli/qemu_install/qemu-5.2.0/bin/qemu-riscv32 -L /home/dingli/toolchain/riscv32/sysroot -g 33334 /home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-slowdebug/jdk/bin/java -version &
```
在需要断点的行前鼠标左击即可打上断点，F5开始调试
Tips：在vscode的`DEBUG CONSLOE`中加上`-exec`即可执行gdb命令，例如：
```
-exec i r
```

我们目前的调试方法是否类似？

**Comment by zifeihan** [comment]
> Hi @zifeihan
> 我之前也做过vscode上gdb的调试的尝试，在`jdk11u`目录下生成`launch.json`，内容为：
> 
> ```json
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "(gdb) Launch",
>             "type": "cppdbg",
>             "request": "launch",
>             "program": "<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/bin/java",
>             "args": [
>                 "-version"],
>             "stopAtEntry": false,
>             "cwd": "<path-to-jdk-src>",
>             "environment": [],
>             "externalConsole": false,
>             "MIMode": "gdb",
>             "miDebuggerPath": "<path-to-toolchain-riscv32>/bin/riscv32-unknown-linux-gnu-gdb",
>             "miDebuggerServerAddress": "localhost:<port>",
>             "setupCommands": [
>                 {
>                     "description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": true,
>                 }
>             ]
>         }
>     ]
> }
> ```
> 
> 主要修改的配置有：
> "program"、"args"、"miDebuggerPath"、"miDebuggerServerAddress"
> 
> 之后在终端中使用命令行启动`qemu java -version`：
> 
> ```
> <path-to-qemu>/bin/qemu-riscv32 -L <path-to-toolchain-riscv32>/sysroot -g <port> <path-to-jdk-src>/jdk11u/build/linux-riscv32-normal-core-slowdebug/jdk/bin/java -version &
> ```
> 
> 在需要断点的行前鼠标左击即可打上断点，F5开始调试
> Tips：在vscode的`DEBUG CONSLOE`中加上`-exec`即可执行gdb命令，例如：
> 
> ```
> -exec i r
> ```
> 
> 我们目前的调试方法是否类似？

是的，方法类似。只是需要在多配置一个`additionalSOLibSearchPath`选项，用来指定相关动态库位置。

**Comment by zifeihan** [comment]
## 使用vscode对openjdk-riscv进行调试

#### 背景：

目前使用gdb调试,稍微麻烦了一些. 如何使用IDE（clion,vscode,netbeans等）进行跨平台调试,主要涉及在IDE机器上是否存在相应版本的gdb, 远程机器上使用的是rv32版本的gdb启动, 如果两端版本不一致,数据通信协议解析不了（已测试）



#### 使用gdb调试教程：

https://github.com/openjdk-riscv/jdk11u/wiki/Debug-with-GDB-in-QEMU-user-mode



#### 使用vscode调试：

##### 步骤如下：

1.首先进入到构建好的JDK镜像的`bin`目录下,然后在后台使用QEMU执行`java -version`,如下

/path/to/qemu/bin/qemu-riscv32 -L /path/to/riscv32/sysroot -g 33334 ./java -version &

2.在vscode中配置debug选项, 进行debug. gdb调试配置如下:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "miDebuggerServerAddress": "localhost:33334",
            "program": "<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/bin/java",
            "args": ["-version"],
            "stopAtEntry": false,
            "cwd": "<path-to-jdk-src>",
            "environment": [],
            "externalConsole": false,
            "additionalSOLibSearchPath": "<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/lib:<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/lib/jli:<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/lib/server",
            "MIMode": "gdb",
            "miDebuggerPath": "<path-to-toolchain-riscv32>/bin/riscv32-unknown-linux-gnu-gdb",
            "setupCommands": [
                {
										"description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

##### 效果如下:

目前进展,可以在linux vscode进行调试. 效果如下:

调试main.c

![image](https://user-images.githubusercontent.com/16839929/132441814-b3d87b02-11aa-4a05-8a27-5f587107dafd.png)



调试bytecodes.cpp

<img width="1356" alt="image-20210908181333463" src="https://user-images.githubusercontent.com/16839929/132493718-6b3a4c53-ebc7-4cfd-94e9-da759e699e95.png">

<img width="1358" alt="image-20210908181517388" src="https://user-images.githubusercontent.com/16839929/132493780-09cb6e7f-da72-4e0e-8477-214ec26f2ea2.png">

**Comment by zhangxiang-plct** [comment]
> ## 使用vscode对openjdk-riscv进行调试
> #### 背景：
> 目前使用gdb调试,稍微麻烦了一些. 如何使用IDE（clion,vscode,netbeans等）进行跨平台调试,主要涉及在IDE机器上是否存在相应版本的gdb, 远程机器上使用的是rv32版本的gdb启动, 如果两端版本不一致,数据通信协议解析不了（已测试）
> 
> #### 使用gdb调试教程：
> https://github.com/openjdk-riscv/jdk11u/wiki/Debug-with-GDB-in-QEMU-user-mode
> 
> #### 使用vscode调试：
> ##### 步骤如下：
> 1.首先进入到构建好的JDK镜像的`bin`目录下,然后在后台使用QEMU执行`java -version`,如下
> 
> /path/to/qemu/bin/qemu-riscv32 -L /path/to/riscv32/sysroot -g 33334 ./java -version &
> 
> 2.在vscode中配置debug选项, 进行debug. gdb调试配置如下:
> 
> ```
> {
>     // Use IntelliSense to learn about possible attributes.
>     // Hover to view descriptions of existing attributes.
>     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "(gdb) Launch",
>             "type": "cppdbg",
>             "request": "launch",
>             "miDebuggerServerAddress": "localhost:33334",
>             "program": "<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/bin/java",
>             "args": ["-version"],
>             "stopAtEntry": false,
>             "cwd": "<path-to-jdk-src>",
>             "environment": [],
>             "externalConsole": false,
>             "additionalSOLibSearchPath": "<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/lib:<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/lib/jli:<path-to-jdk-src>/build/linux-riscv32-normal-core-slowdebug/jdk/lib/server",
>             "MIMode": "gdb",
>             "miDebuggerPath": "<path-to-toolchain-riscv32>/bin/riscv32-unknown-linux-gnu-gdb",
>             "setupCommands": [
>                 {
> 										"description": "Enable pretty-printing for gdb",
>                     "text": "-enable-pretty-printing",
>                     "ignoreFailures": true
>                 }
>             ]
>         }
>     ]
> }
> ```
> 
> ##### 效果如下:
> 目前进展,可以在linux vscode进行调试. 效果如下:
> 
> 调试main.c
> 
> ![image](https://user-images.githubusercontent.com/16839929/132441814-b3d87b02-11aa-4a05-8a27-5f587107dafd.png)
> 
> 调试bytecodes.cpp
> 
> <img alt="image-20210908181333463" width="1356" src="https://user-images.githubusercontent.com/16839929/132493718-6b3a4c53-ebc7-4cfd-94e9-da759e699e95.png">
> 
> <img alt="image-20210908181517388" width="1358" src="https://user-images.githubusercontent.com/16839929/132493780-09cb6e7f-da72-4e0e-8477-214ec26f2ea2.png">

nice！已验证

**Comment by zhangxiang-plct** [comment]
补充一下：目前在P8上调试RV32时，切换进程如果不能鼠标左键点击左边进程栏的进程进行切换时，可以在命令行下输入命令“-exec t 2”进行切换。
