### ISSUE TITLE
初始化wiki页面，将项目的目标、路线图、测试状态等写入到wiki中。

### ISSUE THREAD

**Issue by lazyparser** [openjdk-riscv/jdk11u#2]
## 需要包含

1. 有一个 Home 页面
2. 有一个 roadmap 页面
3. 有一个定期会议的信息（跟东亚时区双周会合并在一起）
4. 有一个/多个面向新实习生/贡献者的介绍信息和入门信息
5. 已经有了相关的资源页，将各位写的文章、做的视频、代码片段等的 url 和标题都贴进去。

## 要求和约束

1. 所有的标题/url都需要ASCII，不要用中文和特殊字符。
2. 做好分钟，确保各自都能添加自己的部分。

有遇到权限问题的话找 @lazyparser

**Comment by lazyparser** [comment]
https://github.com/v8-riscv/v8/wiki

仿照 FutureWei 做的 wiki，非常好

**Comment by shining1984** [comment]
目前基本文档已经都添加齐全。
