### ISSUE TITLE
java.lang.Interger.numberOfLeadingZeros(jint)中的执行流程不一样(执行分支类问题)

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#235]
通过对比bishengjdk和rv32位的log，发现在java.lang.Interger.numberOfLeadingZeros(jint)中执行流程有差异，在32位上会多走一个别的路径，具体差异如下：

![image](https://user-images.githubusercontent.com/3916635/141391923-81c278b5-a5f5-464d-b5e8-7f9e84671786.png)

bishengjdk以 #199 为基准，32位log以 #233 运行输出为基准。

**Comment by shining1984** [comment]
这里涉及到的内容有一个if_ccmplt指令，它作为bytecode主要作用是从栈弹出两个值然后进行比较，如果小于关系成立，那么就跳转到指定的位置。
![image](https://user-images.githubusercontent.com/3916635/141744225-dec2bd23-aeae-4a89-bd19-c18fad504b06.png)

参考文档：https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-6.html#jvms-6.5.if_icmp_cond

阅读目前bishengjdk log的前一万行，里边设计到的if_icmplt的指令的情况，一般都是通过指令先push两个数字进去，然后到if_icmplt进行弹出然后比较，之后进行跳转。

在跳转的时候，有两种情况，一种是只写了条件成功之后的实现，不写不成功之后继续执行的内容；一种是写了条件成功最后的执行内容，还写了不成功之后继续执行内容的实现。对应到具体的log信息中，第一种就是if_icmplt 32，然后紧跟着就是 32 iload_0这种；第二种情况就是 if_icmplt 72，后边紧跟着65 iinc #1 -2这种，65这个就是要在if_icmplt条件不成功的时候要执行的内容。

**Comment by shining1984** [comment]
本次所涉及到的bytecode内容是java.lang.Interger.numberOfLeadingZeros，所以，先找到其源码：
src/java.base/share/classes/java/lang/Integer.java
![image](https://user-images.githubusercontent.com/3916635/141747042-35d3c289-e0c3-4f05-9333-1e02aa326b2a.png)

之后，分别对bishengjdk和rv32g log中的java.lang.Interger.numberOfLeadingZeros进行逐行阅读。在bishengjdk和rv32g log中都各有两个java.lang.Interger.numberOfLeadingZeros函数的字节码，其中第一个函数的字节码在bishengjdk和rv32g log中都一致，它主要是处理了最后一个if条件(if (i >= 1 << 2))  成立的情况。具体代码如下：
![image](https://user-images.githubusercontent.com/3916635/141752214-1f6d2ad5-9a5d-4130-8a74-d7ff1e204470.png)

bishengjdk和rv32g log中java.lang.Interger.numberOfLeadingZeros函数的第二份log不同，也就是本issue中所提到的内容，具体如下：
bishengjdk:
![image](https://user-images.githubusercontent.com/3916635/141752391-b0297494-e14a-48c4-b950-ac7aa8da7556.png)

rv32g:
![image](https://user-images.githubusercontent.com/3916635/141752546-f603b9d7-fea7-48bf-a302-9155813556fd.png)

bishengjdk中的第二个java.lang.Interger.numberOfLeadingZeros实现，它是实现了最后两个if条件成立的情况，if (i >= 1 << 4) 和if (i >= 1 << 2)。rv32g中的第二个java.lang.Interger.numberOfLeadingZeros实现，它是实现了if (i >= 1 << 16)、if (i >= 1 << 8)、if (i >= 1 << 4) 和if (i >= 1 << 2)这四种情况。所以两者的log会有区别，但是其实都对。

**Comment by shining1984** [comment]
完整的java.lang.Interger.numberOfLeadingZeros实现推测应该有5个：1、包含了if (i >= 1 << 2)内容的实现；2、包含了if (i >= 1 << 4)、if (i >= 1 << 2)内容的实现；3、包含了if (i >= 1 << 8)、if (i >= 1 << 4)、if (i >= 1 << 2)内容的实现；4、包含了if (i >= 1 << 16)、if (i >= 1 << 8)、if (i >= 1 << 4)、if (i >= 1 << 2)内容的实现；5、包含if(i <= 0)内容的实现。

**Comment by zhangxiang-plct** [comment]
java.lang.Interger.numberOfLeadingZeros的字节码
```
 0 iload_0
 1 ifgt 15 (+14)
 4 iload_0
 5 ifne 13 (+8)
 8 bipush 32
10 goto 14 (+4)
13 iconst_0
14 ireturn
15 bipush 31
17 istore_1
18 iload_0
19 ldc #91 <65536>
21 if_icmplt 32 (+11)
24 iinc 1 by -16
27 iload_0
28 bipush 16
30 iushr
31 istore_0
32 iload_0
33 sipush 256
36 if_icmplt 47 (+11)
39 iinc 1 by -8
42 iload_0
43 bipush 8
45 iushr
46 istore_0
47 iload_0
48 bipush 16
50 if_icmplt 60 (+10)
53 iinc 1 by -4
56 iload_0
57 iconst_4
58 iushr
59 istore_0
60 iload_0
61 iconst_4
62 if_icmplt 72 (+10)
65 iinc 1 by -2
68 iload_0
69 iconst_2
70 iushr
71 istore_0
72 iload_1
73 iload_0
74 iconst_1
75 iushr
76 isub
77 ireturn

```

**Comment by shining1984** [comment]
此外，需要确认下，翻译成为bytecode时候带上不同的分支这种行为，受不受caller传递参数的影响。

**Comment by shining1984** [comment]
后续这一类问题在 #244 中讨论。

**Comment by shining1984** [comment]
这个问题在#244之中统一进行讨论之后，将在 #246之中进行修改。
