### ISSUE TITLE
指令执行log差异比对记录

### ISSUE THREAD

**Issue by zhangxiang-plct** [openjdk-riscv/jdk11u#239]
下图中，左侧为毕昇JDK的log，右边为rv32的log日志

1、常量池索引值有区别--3240
![image](https://user-images.githubusercontent.com/84717784/141428326-31427cd9-7e7e-4bc5-8db4-5d48c2e7249b.png)

--------------------
2、常量池索引值有区别---3334
![image](https://user-images.githubusercontent.com/84717784/141431740-d93f8fb1-1eba-4d24-b04d-0fe645332578.png)

---------------

3、3413行
![image](https://user-images.githubusercontent.com/84717784/141432030-30ed402d-242a-4420-99b7-270c046c22b5.png)

这个比对通过工具检测，结论是毕昇JDK的log打印出现遗漏，rv32的log显示是正常的

![image](https://user-images.githubusercontent.com/84717784/141446373-20655453-d431-4b1e-9c74-d72ca84790f4.png)

-----------------------------
4、常量池索引值有区别
![image](https://user-images.githubusercontent.com/84717784/141432726-51405374-f1a2-4c1a-a141-b124491cc98a.png)

------------------------------
5、rv32中出现了Random方法，而毕昇JDK中前1w多行均未出现。4743行
![image](https://user-images.githubusercontent.com/84717784/141445635-c2c67366-3509-479c-af71-a69746fa8eb4.png)

-------------
6、4652行
![image](https://user-images.githubusercontent.com/84717784/141449901-4b92a924-d02e-4ec9-b794-a31407a44580.png)
通过字节码工具查看，rv32中出现的指令没有问题，而毕昇JDK中的‘fast_iload’并未出现。这个原因暂时不清楚。

![image](https://user-images.githubusercontent.com/84717784/141450209-d958c62f-7e48-4724-9bbd-7e9e14f48b87.png)

--------------------
在4778行之后，rv32log中的指令就与毕昇JDK的log显示差距过大，其中rv32中出现的AtomicLong、Random、Reflection等方法在毕昇JDK的log前1w行均未出现（由于log长度限制）。
所以猜测，rv32在4778行前后出现错误，导致后续指令执行与毕昇JDK的差距过大。

**Comment by zifeihan** [comment]
> 通过字节码工具查看，rv32中出现的指令没有问题，而毕昇JDK中的‘fast_iload’并未出现。这个原因暂时不清楚。

JVM在执行时，会将部分 iload 指令替换 fast_iload 指令，具体是如何替换的需要了解一下。

**Comment by zhangxiang-plct** [comment]
> > 通过字节码工具查看，rv32中出现的指令没有问题，而毕昇JDK中的‘fast_iload’并未出现。这个原因暂时不清楚。
> 
> JVM在执行时，会将部分 iload 指令重写为 fast_iload 指令，具体转换逻辑请参考：https://www.cnblogs.com/mazhimazhi/p/15352941.html

那么为什么rv32中没有出现重写，而毕昇JDK中出现了重写呢？就字节码工具来看，没有这个过程。

**Comment by zhangxiang-plct** [comment]
6、
![image](https://user-images.githubusercontent.com/84717784/141642389-306044ce-5d00-4118-85b8-78603ead47d3.png)
其中`ifne 120`正常情况下应该是跳转到120（毕昇JDk对应的情况）。rv32此处并没有正常跳转。

**Comment by zhangxiang-plct** [comment]
> 6、 ![image](https://user-images.githubusercontent.com/84717784/141642389-306044ce-5d00-4118-85b8-78603ead47d3.png) 其中`ifne 120`正常情况下应该是跳转到120（毕昇JDk对应的情况）。rv32此处并没有正常跳转。

这里的120 表示
(src/hotspot/share/interpreter/bytecodeTracer.cpp:495)
```
    case Bytecodes::_ifeq:
    case Bytecodes::_ifnull:
    case Bytecodes::_iflt:
    case Bytecodes::_ifle:
    case Bytecodes::_ifne:
    case Bytecodes::_ifnonnull:
    case Bytecodes::_ifgt:
    case Bytecodes::_ifge:
    case Bytecodes::_if_icmpeq:
    case Bytecodes::_if_icmpne:
    case Bytecodes::_if_icmplt:
    case Bytecodes::_if_icmpgt:
    case Bytecodes::_if_icmple:
    case Bytecodes::_if_icmpge:
    case Bytecodes::_if_acmpeq:
    case Bytecodes::_if_acmpne:
    case Bytecodes::_goto:
    case Bytecodes::_jsr:
      st->print_cr(" %d", bci + get_short());
      break;
```
其中bci对应了指令的偏移量，而`get_short()--> get_Java_u2(address p) { return swap_u2(get_native_u2(p))--->}`。

**Comment by zhangxiang-plct** [comment]
> 6、 ![image](https://user-images.githubusercontent.com/84717784/141642389-306044ce-5d00-4118-85b8-78603ead47d3.png) 其中`ifne 120`正常情况下应该是跳转到iconst_1到还是跳转到“120”对应的指令？
> 
> ![image](https://user-images.githubusercontent.com/84717784/141988061-a2fea2e7-ae6f-4a45-9982-c44b4550414c.png)

经过比对研究，这个“34 ifnull（+86）”下一条指令应该是跳转到120（34+86）指令处，所以此处是跳转出错。

**Comment by zhangxiang-plct** [comment]
关于常量池索引值的差异问题，在毕昇JDk版本回退到810e92之后已消失，所以差异是毕昇JDK的版本差异导致。
