### ISSUE TITLE
lcmp 指令修复

### ISSUE THREAD

**Issue by zifeihan** [openjdk-riscv/jdk11u#240]
调试过程中发现 lcmp 指令也有关于 Long 类型长度的问题，可能也需要修改。

**Comment by zifeihan** [comment]
参考 ARM32 和X86 32都有类似对 lcmp 该指令做特殊处理。

**Comment by DingliZhang** [comment]
在不同架构下的lcmp中都含有pop_l函数，也就是弹出栈顶的long类型数据，而我们需要传入两个寄存器来保存long类型的值，可以参考下arm和x86的32位版实现
### ARM
pop_l的定义：
https://github.com/openjdk-riscv/jdk11u/blob/f336c729e35b6793d0910beec167b2c739ec95e7/src/hotspot/cpu/arm/interp_masm_arm.cpp#L427-L431
其中RegisterSet是个寄存器集合，使用一个32位的数来表示所选的寄存器集合，encoding中二进制为1的位置代表了所选寄存器的索引。
pop的定义：
https://github.com/openjdk-riscv/jdk11u/blob/f336c729e35b6793d0910beec167b2c739ec95e7/src/hotspot/cpu/arm/macroAssembler_arm.hpp#L424-L427
其中`ldmia`是批量加载指令（from https://developer.arm.com/documentation/dui0068/b/BABEFCIB ），会将SP移动到相应的位置，所以不需要rv32的pop_l中最后的addi指令：
![image](https://user-images.githubusercontent.com/19571377/142149260-efc05cab-716d-4236-9f1d-79cd182b02bd.png)

### X86
pop_l的定义：
https://github.com/openjdk-riscv/jdk11u/blob/f336c729e35b6793d0910beec167b2c739ec95e7/src/hotspot/cpu/x86/interp_masm_x86.cpp#L662-L665
pop的定义：
https://github.com/openjdk-riscv/jdk11u/blob/f336c729e35b6793d0910beec167b2c739ec95e7/src/hotspot/cpu/x86/assembler_x86.cpp#L4078-L4081
其中`emit_int8(0x58 | encode)`由gdb调试可以计算出opcode为0x88，代表了mov指令：
![image](https://user-images.githubusercontent.com/19571377/142155016-0757d9be-aa97-44d3-9dff-3dfbd3366894.png)

对于rv32来说应该也需要传入两个寄存器的值，目前还在修改之中。

**Comment by DingliZhang** [comment]
已提交PR #251 

### pop_l
目前代码中的pop_l逻辑是有问题的，如果传入的参数为 x11，则会将x10与x11都设置为所需要的long类型数据的低4字节数据导致冲突，因此需要传入两个寄存器。
![image](https://user-images.githubusercontent.com/19571377/142557069-b7041f48-a6e2-4658-b6bf-13b30bbc2b1a.png)
修改位于 https://github.com/openjdk-riscv/jdk11u/pull/251/commits/f95cb8f486bd1753f6fb29e2a097b5d869ebca4e

### lcmp
对于lcmp来说，判断逻辑位于 MacroAssembler::cmp_l2i  中，在修复了pop_l之后，需要先判断两个比较数据的高32位，之后再比较低32位。
下图为修复lcmp前后汇编代码对比，左侧为修复前pop_l逻辑是有寄存器重复问题的，修复后使用4个寄存器分别存储了两个比较数的高低4字节，之后先比较数据的高32位，之后再比较低32位。
![QQ截图20211119114037](https://user-images.githubusercontent.com/19571377/142561471-70a1084a-e300-4e62-af0b-50540f3294f8.jpg)
提交PR后，与之前issue中 https://github.com/openjdk-riscv/jdk11u/issues/239#issuecomment-970353134 的 java.util.concurrent.ConcurrentHashMap.addCount 对比，首个字节码的索引位置 `4694` 与 bishengJDK一致，最后的报错没有变化

![image](https://user-images.githubusercontent.com/19571377/142560263-006f9771-ffa6-4b5e-946b-9f44078b7ac6.png)
![image](https://user-images.githubusercontent.com/19571377/142563058-15f85d86-cb03-4714-b378-649a171de2ef.png)

**Comment by DingliZhang** [comment]
pop_l修改导致后续一些指令逻辑需要修复，新开了issue进行讨论：#252

**Comment by zifeihan** [comment]
针对最新的代码已验证，汇编逻辑如下：
```
----------------------------------------------------------------------
lcmp  148 lcmp  [0x3cccccc0, 0x3ccccd80]  192 bytes

  0x3cccccc0: lw	a0,0(s4)
  0x3cccccc4: lw	a1,4(s4)
  0x3cccccc8: addi	s4,s4,8
  0x3ccccccc: addi	s4,s4,-4
  0x3cccccd0: sw	t0,0(s4)
  0x3cccccd4: addi	s4,s4,-4
  0x3cccccd8: sw	a0,0(s4)
  0x3cccccdc: lui	a0,0x3fe0f
  0x3ccccce0: addi	a0,a0,392 # 0x3fe0f188
  0x3ccccce4: lui	t0,0x0
  0x3ccccce8: addi	t0,t0,1 # 1
  0x3cccccec: amoadd.w.aqrl	zero,t0,(a0)
  0x3cccccf0: lw	a0,0(s4)
  0x3cccccf4: addi	s4,s4,4
  0x3cccccf8: lw	t0,0(s4)
  0x3cccccfc: addi	s4,s4,4
  0x3ccccd00: jal	ra,0x3ccb7454
  0x3ccccd04: lw	a2,0(s4)
  0x3ccccd08: lw	a3,4(s4)
  0x3ccccd0c: addi	s4,s4,8


 如果a < b 则写入1, 如果 a > b 则写入 -1, a = b 则写入 0
 a = a1:a0
 b = a3:a2

  如果a1小于a3，则向t0 写入1，否则写入0
  0x3ccccd10: slt	t0,a1,a3

  如果 t0 不等于0，即：a1小于a3，则跳转到 0x3ccccd40（done） t0 为 1
  0x3ccccd14: bnez	t0,0x3ccccd40

  如果 a3 小于 a1 ，则向 t0 写入1，否则写入0
  0x3ccccd18: slt	t0,a3,a1

  此时存在两种结果，一种是a3小于a1（取反后为-1），另一种是a3等于a1（取反后为0），对 t0 中的值取反 并将结果存放在 t0 中
  0x3ccccd1c: neg	t0,t0

  如果 t0 不等于0，即：a3小于a1，则跳转到 0x3ccccd40（done） t0 为 -1
  0x3ccccd20: bnez	t0,0x3ccccd40


  // 如下情况为 a1 等于 a3 ，说明数据的高四字节相等,以下比较低四字节

  如果 a1 小于0（为负数情况），则将tmp（t1） 写入1, 否则写入0
  0x3ccccd24: sltz	t1,a1


  如果 a0 小于 a2, 则向 t0 写入1，否则写入0
  0x3ccccd28: sltu	t0,a0,a2

  如果 t0 不等于0，即：a0 小于 a2，则跳转到 0x3ccccd38（判断是否为负数）
  0x3ccccd2c: bnez	t0,0x3ccccd38

  如果 a2 小于 a0, 则向 t0 写入1，否则写入0
  0x3ccccd30: sltu	t0,a2,a0

  此时存在两种情况，一种是 a2 小于 a0 （取反后为-1） 另一种是 a2 等于 a0（取反后为0）
  如果a为整数的情况下，则需要向 t0 写入-1，如果为a为负数的情况下，

  0x3ccccd34: neg	t0,t0

  判断 t1 是否为0，如果为0 代表不是负数，如果不为负数的话，那么低四字节的数据，大的就大，小的就小。 如果为负数的话，第四字节大的反而小
  0x3ccccd38: beqz	t1,0x3ccccd40

  如果为 t1 为负数，低四字节大的数据反而小，因此需要将t0中的值取反
  0x3ccccd3c: neg	t0,t0



  0x3ccccd40: mv	a0,t0
  0x3ccccd44: lbu	t0,1(s6)
  0x3ccccd48: addi	s6,s6,1
  0x3ccccd4c: lui	t1,0x0
  0x3ccccd50: addi	t1,t1,1024 # 0x00000400
  0x3ccccd54: add	t1,t0,t1
  0x3ccccd58: slli	t1,t1,0x2
  0x3ccccd5c: add	t1,s5,t1
  0x3ccccd60: lw	t1,0(t1)
  0x3ccccd64: jr	t1
  0x3ccccd68: sw	a1,28(s1)
  0x3ccccd6a: sw	a1,28(s1)
  0x3ccccd6c: sw	a1,28(s1)
  0x3ccccd6e: sw	a1,28(s1)
  0x3ccccd70: sw	a1,28(s1)
  0x3ccccd72: sw	a1,28(s1)
  0x3ccccd74: sw	a1,28(s1)
  0x3ccccd76: sw	a1,28(s1)
  0x3ccccd78: sw	a1,28(s1)
  0x3ccccd7a: sw	a1,28(s1)
  0x3ccccd7c: sw	a1,28(s1)
  0x3ccccd7e: sw	a1,28(s1)
```
