### ISSUE TITLE
pop_l修复之后后续指令逻辑修复

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#252]
pop_l修复之后，后续的指令需要用的到其结果，但是目前有部分模板/生成器没有针对long类型数据对rv32进行处理，需要进行修复，包括：
```
void TemplateTable::lop2(Operation op)  // 操作两个long类型数的生成器
void TemplateTable::lmul()   // 栈顶两long型数值相乘，而且结果进栈
void TemplateTable::ldiv()  // 栈顶两long型数值相除，而且结果进栈
void TemplateTable::lrem()  // 栈顶两long型数值取模，而且结果进栈
void TemplateTable::lshl()  // long型数值左移指定位数，而且结果进栈
void TemplateTable::lshr()  //  long型数值带符号右移指定位数，而且结果进栈
void TemplateTable::lushr()  //  long型数值无符号右移指定位数，而且结果进栈
```

**Comment by DingliZhang** [comment]
### lop2
lop2是操作两个long类型数的生成器，包含的逻辑有：
```
add  //加
sub  //减
mul  //乘
_and //与
_or  //或
_xor //异或
```

**Comment by DingliZhang** [comment]
可以用gcc生成未链接的文件，再objdump出汇编代码来查看rv32对64位数操作的逻辑。
以add为例，新建如下的`1.c`文件：
```
#include <stdint.h>
int64_t add64s(int64_t a, int64_t b)
{
	return a+b;
}
```
之后执行：
```
$ riscv32-unknown-linux-gnu-gcc -march=rv32imafd -O2 -c -o 1.o 1.c
$ riscv32-unknown-linux-gnu-objdump -d -M no-aliases 1.o
```
即可得到汇编码：
```
00000000 <add64s>:
   0:   00050793                addi    a5,a0,0
   4:   00c50533                add     a0,a0,a2
   8:   00f537b3                sltu    a5,a0,a5
   c:   00d585b3                add     a1,a1,a3
  10:   00b785b3                add     a1,a5,a1
  14:   00008067                jalr    zero,0(ra)
```
其他的指令类似。目前已修改好lop2下全部指令，正在验证。

**Comment by zhangxiang-plct** [comment]
lshl字节码修复：
参考 [反汇编方法](https://github.com/openjdk-riscv/jdk11u/issues/252#issuecomment-975325265) 获取到汇编代码
**左移源码**
```
#include<stdint.h>
uint64_t sllu(uint64_t a,uint32_t b){
return a<<b;
}
```

```
00000000 <sllu>:
   0:   fe060793                addi    a5,a2,-32
   4:   0007c863                blt     a5,zero,14 <.L2>
   8:   00f515b3                sll     a1,a0,a5
   c:   00000513                addi    a0,zero,0
  10:   00008067                jalr    zero,0(ra)

00000014 <.L2>:
  14:   01f00713                addi    a4,zero,31
  18:   00155793                srli    a5,a0,0x1
  1c:   40c70733                sub     a4,a4,a2
  20:   00e7d7b3                srl     a5,a5,a4
  24:   00c595b3                sll     a1,a1,a2
  28:   00b7e5b3                or      a1,a5,a1
  2c:   00c51533                sll     a0,a0,a2
  30:   00008067                jalr    zero,0(ra)
```
**分析汇编代码：**
```
long类型数据长度为64位，8字节，在riscv32中，分两个寄存器保存：x13保存高四字节数据，x12保存低四字节数据。所以位移数需要分是否大于32来进行处理。

   0:   fe060793                addi    a5,a2,-32
   4:   0007c863                blt     a5,zero,14 <.L2>
   8:   00f515b3                sll     a1,a0,a5
   c:   00000513                addi    a0,zero,0

当a2>32时，那么低4字节的数据直接置0，将低4字节溢出的数据存到高4字节中去。

 14:   01f00713                addi    a4,zero,31
  18:   00155793                srli    a5,a0,0x1
  1c:   40c70733                sub     a4,a4,a2
  20:   00e7d7b3                srl     a5,a5,a4
  24:   00c595b3                sll     a1,a1,a2
  28:   00b7e5b3                or      a1,a5,a1
  2c:   00c51533                sll     a0,a0,a2
  30:   00008067                jalr    zero,0(ra)
当a2<32时，低4字节数据做正常的左移处理，高4字节需要保留低4字节溢出的数据。
```
```
**修改的源码**
void TemplateTable::lshl()
{
  transition(itos, ltos);
  // shift count is in x10
  __ pop_l(x12, x13);
  Label blt_branch,done;
  __ addi(x15,x10,-32);
  __ bltz(x15,blt_branch);
  __ sll(x13,x12,x15);
  __ mv(x12,0);
  __ beqz(zr,done);
  __ bind(blt_branch);
  __ mv(x14,31);
  __ srli(x15,x12,0x1);
  __ sub(x14,x14,x10);
  __ srl(x15,x15,x14);
  __ sll(x13,x13,x10);
  __ orr(x13,x15,x13);
  __ sll(x12, x12, x10);

  __ bind(done);
  __ mv(x10,x12);
  __ mv(x11,x13);
}


```
已提 [pr257](https://github.com/openjdk-riscv/jdk11u/pull/257).麻烦 @DingliZhang @shining1984 @zifeihan 帮忙review

**Comment by zhangxiang-plct** [comment]
基于 [shl左移分析](https://github.com/openjdk-riscv/jdk11u/issues/252#issuecomment-977462869) 的修复原理，对lshr以及lushr 进行修复。
已提pr [260](https://github.com/openjdk-riscv/jdk11u/pull/260) 。
修复后对当前进度无影响。

**Comment by zhangxiang-plct** [comment]
基于 [shl左移分析](https://github.com/openjdk-riscv/jdk11u/issues/252#issuecomment-977462869) 的修复原理，对long的取反指令 lneg 进行修复。

**C语言源码**
```
uint64_t lneg(uint64_t a){

    return ~a;
}
```
**反汇编后的汇编代码**
```
000000d4 <lneg>:
  d4:   fff54513                xori    a0,a0,-1
  d8:   fff5c593                xori    a1,a1,-1
  dc:   00008067                jalr    zero,0(ra)
```
**修复代码**
```
void TemplateTable::lneg()
{
  transition(ltos, ltos);
  __ neg(x10, x10);
  __ neg(x11, x11);
}
```
修复后对当前进度无影响。

**Comment by zhangxiang-plct** [comment]
> 基于 [shl左移分析](https://github.com/openjdk-riscv/jdk11u/issues/252#issuecomment-977462869) 的修复原理，对long的取反指令 lneg 进行修复。
> 
> **C语言源码**
> 
> ```
> uint64_t lneg(uint64_t a){
> 
>     return ~a;
> }
> ```
> 
> **修复代码**
> 
> ```
> void TemplateTable::lneg()
> {
>   transition(ltos, ltos);
>   __ neg(x10, x10);
>   __ neg(x11, x11);
> }
> ```
> 
> 已提pr [256](https://github.com/openjdk-riscv/jdk11u/pull/265) 修复后对当前进度无影响。

参考手册关于取反指令“neg”的定义
![image](https://user-images.githubusercontent.com/84717784/145394387-83e62a83-05f6-4b68-ad1b-04c3d35ec504.png)
考虑long值如果是有符号数，当为负数时，符号位是在高字节的，根据负数的补码取法，先对原码取反然后+1，然而事实上，符号位是在高字节的，` __ neg(x10, x10)`  这个操作取反将1加在了高字节上，实际上这个+1理当加在低字节上。

为了避免有符号无符号对补码的干扰，用异或的操作来取反：

```
void TemplateTable::lneg()
{
  transition(ltos, ltos);
  __ xori(x10, x10, -1);
  __ xori(x11, x11, -1);
  
}
```

**Comment by zhangxiang-plct** [comment]
> 基于 [shl左移分析](https://github.com/openjdk-riscv/jdk11u/issues/252#issuecomment-977462869) 的修复原理，对long的取反指令 lneg 进行修复。
> 
> **C语言源码**
> 
> ```
> uint64_t lneg(uint64_t a){
> 
>     return ~a;
> }
> ```
> 
> **修复代码**
> 
> ```
> void TemplateTable::lneg()
> {
>   transition(ltos, ltos);
>   __ neg(x10, x10);
>   __ neg(x11, x11);
> }
> ```
> 
> 已提pr [256](https://github.com/openjdk-riscv/jdk11u/pull/265) 修复后对当前进度无影响。

参考手册关于取反指令“neg”的定义
![image](https://user-images.githubusercontent.com/84717784/145394387-83e62a83-05f6-4b68-ad1b-04c3d35ec504.png)
考虑long值如果是有符号数，当为负数时，符号位是在高字节的，根据负数的补码取法，先对原码取反然后+1，然而事实上，符号位是在高字节的，` __ neg(x10, x10)`  这个操作取反将1加在了高字节上，实际上这个+1理当加在低字节上。

为了避免有符号无符号对补码的干扰，用异或的操作来取反：

```
void TemplateTable::lneg()
{
  transition(ltos, ltos);
  __ xori(x10, x10, -1);
  __ xori(x11, x11, -1);
  
}
```

**Comment by zhangxiang-plct** [comment]
对lmul指令进行修改
**C语言源码**
```
uint64_t lmul(uint64_t a,uint64_t b){


return a*b;
}
```

**反汇编代码**
```
  b4:   02a686b3                mul     a3,a3,a0
  b8:   02c585b3                mul     a1,a1,a2
  bc:   02c537b3                mulhu   a5,a0,a2
  c0:   00d585b3                add     a1,a1,a3
  c4:   02c50533                mul     a0,a0,a2
  c8:   00f585b3                add     a1,a1,a5
  cc:   00008067                jalr    zero,0(ra)
```


**修改代码**
```
void TemplateTable::lmul()
{
  transition(ltos, ltos);
 __ pop_l(x12, x13);
 __ mul(x13, x13, x10);
 __ mul(x11, x11, x12);
 __ mulhu(x15, x10, x12);
 __ add(x11, x11, x13);
 __ mul(x10, x10,x12);
 __ add(x11, x11, x15);
}

```
具体影响结果还在验证中

**Comment by DingliZhang** [comment]
参照 @zhangxiang-plct 的结果，进行了进一步的修改，提交了 https://github.com/openjdk-riscv/jdk11u/pull/306

测试脚本：
```
public class Foo {

    public static void main(String[] args) {
        long c = 100000000000L;
        long d = 10000000000L;
        int a = (int)(c%d);
        System.out.println(a);
    }
}
```

使用bootjdk进行编译，rv32g-dev的jdk运行java命令，可以看到修复前后结果的对比：（左为修复前j结果为0，右为修复后结果为10）：

![6Q_$@~N`NK3LIYQSWXY1W@Y](https://user-images.githubusercontent.com/19571377/148354235-49b7951f-122f-4e7b-a686-46a84b46c201.png)

**Comment by zhangxiang-plct** [comment]
基于 [@DingliZhang comment](https://github.com/openjdk-riscv/jdk11u/issues/252#issuecomment-1006379429)的想法以及 [pr306](https://github.com/openjdk-riscv/jdk11u/pull/306) .
对lrem指令进行修改：
测试脚本
```
public class Foo {

    public static void main(String[] args) {
        long c = 500000000000000L;
        long d = 50000000000000L;
        int a = (int)(c%d);
        System.out.println(a);
    }
}
```
使用bootjdk进行编译，rv32g-dev的jdk运行java命令，可以看到修复前后结果的对比：（图1为修复前的结果）
![Uploading image.png…]()
