### ISSUE TITLE
关于在不同机器执行字节码结果不一致的问题分析(一)

### ISSUE THREAD

**Issue by zifeihan** [openjdk-riscv/jdk11u#284]
#### 背景：

我们在通过对比 BishengJDK 的字节码和 OpenJDK for RV32G 的字节码时，发现二者的字节码在 大约 76775 行的 static jint java.lang.StringLatin1.indexOf(jobject, jint, jint) 方法里面执行的字节码不一致。BishengJDK 字节码使用的是：https://github.com/openjdk-riscv/jdk11u/issues/278 中最新的字节码日志。

通过将展开差异的字节码，发现是 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint)` 方法实际执行的字节码有差异。

<img width="1920" alt="image-20211222152210688" src="https://user-images.githubusercontent.com/16839929/147072362-2367cd92-31f0-457c-90fc-b062b0826f89.png">

#### 问题排查：

发现问题之后，同事都在自己的环境上输出了 OpenJDK for RV32G 的字节码日志。每位同事执行的字节码大约 76775 行的 static jint java.lang.StringLatin1.indexOf(jobject, jint, jint) 方法的字节码也都与 BishengJDK 在此处的字节码不同，甚至同事之间执行的的 OpenJDK for RV32G 字节码也都不同，即同事之间使用相同命令执行的结果都不能保持一致。

1. 梳理调用  76775 行的 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint) ` 调用关系

   在这里我没有好的办法，我是向上推导是谁调用了 76775 行的 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint) `方法。调用关系如下：`static void java.lang.ClassLoader.initLibraryPaths()` 最终调用到了 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint)` 方法。

   ```
   static jint java.lang.StringLatin1.indexOf(jobject, jint, jint)
   	virtual jint java.lang.String.indexOf(jint, jint)
   		virtual jint java.lang.String.indexOf(jint)
   			static jobject java.lang.ClassLoader.initializePath(jobject)
   				static void java.lang.ClassLoader.initLibraryPaths()
   ```

2. 我们通过查看 java 方法`static void java.lang.ClassLoader.initLibraryPaths()` 源码，并且也能从该源码下钻到 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint)` 。`static void java.lang.ClassLoader.initLibraryPaths()` 源码如下：

   ```
       static void initLibraryPaths() {
           usr_paths = initializePath("java.library.path");
           sys_paths = initializePath("sun.boot.library.path");
       }
   ```

3. 我们查看 java 方法 `static jobject java.lang.ClassLoader.initializePath(jobject) `源码，看到方法内的变量 `ldPath` 是通过 `String ldPath = System.getProperty(propName, "");` 方式获取的。

   
   ```
   private static String[] initializePath(String propName) {
           String ldPath = System.getProperty(propName, "");
           int ldLen = ldPath.length();
           char ps = File.pathSeparatorChar;
           int psCount = 0;
   
           if (ClassLoaderHelper.allowsQuotedPathElements &&
               ldPath.indexOf('\"') >= 0) {
               // First, remove quotes put around quoted parts of paths.
               // Second, use a quotation mark as a new path separator.
               // This will preserve any quoted old path separators.
               char[] buf = new char[ldLen];
               int bufLen = 0;
               for (int i = 0; i < ldLen; ++i) {
                   char ch = ldPath.charAt(i);
                   if (ch == '\"') {
                       while (++i < ldLen &&
                           (ch = ldPath.charAt(i)) != '\"') {
                           buf[bufLen++] = ch;
                       }
                   } else {
                       if (ch == ps) {
                           psCount++;
                           ch = '\"';
                       }
                       buf[bufLen++] = ch;
                   }
               }
               ldPath = new String(buf, 0, bufLen);
               ldLen = bufLen;
               ps = '\"';
           } else {
               for (int i = ldPath.indexOf(ps); i >= 0;
                    i = ldPath.indexOf(ps, i + 1)) {
                   psCount++;
               }
           }
   
           String[] paths = new String[psCount + 1];
           int pathStart = 0;
           for (int j = 0; j < psCount; ++j) {
               int pathEnd = ldPath.indexOf(ps, pathStart);
               paths[j] = (pathStart < pathEnd) ?
                   ldPath.substring(pathStart, pathEnd) : ".";
               pathStart = pathEnd + 1;
           }
           paths[psCount] = (pathStart < ldLen) ?
               ldPath.substring(pathStart, ldLen) : ".";
           return paths;
       }
   ```

   我们可以看到上述代码中 `String ldPath = System.getProperty(propName, "");` 来获取环境变量信息，我们知道有些 java 的环境变量信息与当前编译后的 JDK/JRE 所在的目录有关系，因为在调试OpenJDK 时候，大家的OpenJDK 项目路径通常不在一个目录，例如：项目在 `/home/$USER/jdk11u`目录，编译后的 JDK 在`/home/zifeihan/jdk11u/build/linux-riscv32-normal-core-slowdebug`。因此导致了传递给  `java.lang.StringLatin1.indexOf` 方法的参数不一致。
   
4. 验证 `System.getProperty("java.library.path") ` 与环境的关系，我们写一个简单的程序来打印该变量的值：

   ```
   package codec.fun.learn;
   
   public class T {
       public static void main(String[] args) {
           System.out.println(System.getProperty("java.library.path"));
           System.out.println(System.getProperty("sun.boot.library.path"));
       }
   }
   
   本地 JDK11 输出结果为：
   /Users/zifeihan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
   /Users/zifeihan/program/zulu-11.jdk/zulu-11.jdk/Contents/Home/lib
   
   更换 JDk 为JDK8的输出结果：
   /Users/zifeihan/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
   /Users/zifeihan/program/zulu-8.jdk/Contents/Home/jre/lib
   ```

5. 至此我们既可以知道 再对比BishengJDK 的字节码和 OpenJDK for RV32G 的字节码时，二者的字节码在大约 76775 行的` static jint java.lang.StringLatin1.indexOf(jobject, jint, jint)` 方法里面实际执行的字节码差异 是因为项目所在的目录不一致的原因导致的。

#### 本地验证：

1. 我通过将 BishengJDK 编译后的 JDK 目录重命名和 OpenJDK for RV32 的目录一致，然后再次使用 https://github.com/openjdk-riscv/jdk11u/issues/278 中的方法打印 BishengJDK 的字节码，然后使用  BishengJDK 的字节码和  OpenJDK for RV32 的字节码进行对比，发现之前在大约 76775 行的 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint) `方法中的字节码不一致的问题消除了。并且通过对比工具发现，新的差异在10W 行字节码之后了。
2. 如果我们不把 BishengJDK 编译后的 JDK 目录重命名和 OpenJDK for RV32 的目录一致，除了上述大约 76775 行的 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint) `方法中的字节码不一致的问题，在字节 78905 行的 `static void java.lang.invoke.MethodHandleStatics.<clinit>() ` 执行过程中也会存在字节码不一致的情况，看源码中也有对环境变量信息的操作，推测也是类似情况。（如果在目录都一致时则没有这两个差异）。因此我们也可以忽律上述两处差异，抛开这两处差异，最新的差异就到10W行之后了。
3. 为了说明是项目位置导致的上述问题，我们将 bishengJDK 或者 OpenJDK for RV32 放在一台机器的不同位置，及目录不同。然后在打印字节码日志，可以看到最终二者的字节日志结果也是在大概 76775 行的 `static jint java.lang.StringLatin1.indexOf(jobject, jint, jint) `方法字节码是不一致的。

#### 结论：

当前此处不一致的问题是 `大约76775 行的 static jint java.lang.StringLatin1.indexOf(jobject, jint, jint)  `该函数的第一个参数是一个变量，该变量取决于当前项目所在的路径，因为可能在不同的路径下执行，所以导致传入的参数不一致。

**Comment by zifeihan** [comment]
@shining1984 @DingliZhang @zhangxiang-plct 期待大家的对比结果。
我把bisheng的目录换成了rv32g类似的目录，然后对比两边的字节码日志，差异应该在10万行后了。
![image](https://user-images.githubusercontent.com/16839929/146866182-09585641-4e59-40da-ab9a-6e0b5ecb9d17.png)

**Comment by zhangxiang-plct** [comment]
已验证，目前正调试10w行log的差异问题

**Comment by DingliZhang** [comment]
将bishengJDK的目录改为和rv32g的一致：
```
/home/dingli/jdk11u_bisheng/build/linux-riscv32-normal-core-slowdebug/jdk/bin
```
结果比对：

![image](https://user-images.githubusercontent.com/19571377/146939258-08a3c1a6-c54a-4c2b-971d-50a2b87b3bae.png)

**Comment by zhangxiang-plct** [comment]
1、通过对比发现目前可能存在的差异点：
k9：129411   131452  140689 157299  160064（指令数）
由于中间涉及多线程问题，会将方法打乱导致部分指令顺序乱序，通过初步整理分析，得出结论：
初步预判直到最后才产生差异（指rv32指令在229483处结束）

2、其次，在 [269](https://github.com/openjdk-riscv/jdk11u/issues/269) 中的索引值不一致问题已经解决，由于毕昇JDK的版本回退，目前毕昇JDK与rv32之间不存在索引值不一致的问题了。
