### ISSUE TITLE
关于 virtual jint java.util.ImmutableCollections$SetN.probe(jobject) 方法中跳转逻辑不一致的问题

### ISSUE THREAD

**Issue by zifeihan** [openjdk-riscv/jdk11u#285]
在 10W 行后 `virtual jint java.util.ImmutableCollections$SetN.probe(jobject)` 方法中字节码存在跳转不一致的问题，按理来说该方法的字节码应该类似 bishengJDK 的执行结果，但是现在 `ifnonnull` 跳转到了不符合预期的位置。
![image](https://user-images.githubusercontent.com/16839929/146904409-f5d10f1b-cd90-483f-bd75-81041b2fe33d.png)

**Comment by zhangxiang-plct** [comment]
经过比对发现，
![image](https://user-images.githubusercontent.com/84717784/146915232-1551541d-8e8f-42f8-9185-b5802ba6ecdb.png)
![image](https://user-images.githubusercontent.com/84717784/146915409-9dcc3cde-4788-4846-a5a1-5d31798eafd8.png)
这两处会出现同样的跳转差异问题。

**Comment by zifeihan** [comment]
具有差异的字节码对应的函数源码如下：
```
// returns index at which element is present; or if absent,
        // (-i - 1) where i is location where element should be inserted.
        // Callers are relying on this method to perform an implicit nullcheck
        // of pe
        private int probe(Object pe) {
            int idx = Math.floorMod(pe.hashCode(), elements.length);
            while (true) {
                E ee = elements[idx];
                if (ee == null) {
                    return -idx - 1;
                } else if (pe.equals(ee)) {
                    return idx;
                } else if (++idx == elements.length) {
                    idx = 0;
                }
            }
        }
```
通过调试，发现是因为对象的 hashcode 在不同机器会存在不一致的情况，然后通过`int idx = Math.floorMod(pe.hashCode(), elements.length);` 来进行类似的取模运算，最终取模的值可能会相同，为了保证数据能够正确存放到 `elements` 数组里面，所以会进行如下的重试：
```
while (true) {
                E ee = elements[idx];
                if (ee == null) {
                    return -idx - 1;
                } else if (pe.equals(ee)) {
                    return idx;
                } else if (++idx == elements.length) {
                    idx = 0;
                }
            }
```
由此我们可以看到这段重试的逻辑是可能正常发生的，此issue中 BishengJDK 字节码和 OpenJDK for RV32G的差异可以忽略。
