### ISSUE TITLE
请问现在的版本能直接在Riscv系统环境下安装吗？

### ISSUE THREAD

**Issue by chen-coco** [openjdk-riscv/jdk11u#293]
有一块riscv的板子，能否直接安装呢？

**Comment by shining1984** [comment]
请问是64位的板子么？
如果是64位的板子，可以参考下：毕昇JDK 11 for RV64GC在D1开发板构建过程 - 知乎  https://zhuanlan.zhihu.com/p/386123758

32位目前我们还在移植中，只能运行Zero模式。可以参考：https://zhuanlan.zhihu.com/p/347698335

**Comment by chen-coco** [comment]
我按这个试一下，蟹蟹

**Comment by chen-coco** [comment]
我按这个试一下，蟹蟹😚
