### ISSUE TITLE
javac调试过程

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#302]
在提交了 https://github.com/openjdk-riscv/jdk11u/pull/301 以后，目前slowdebug版本的 `java -version` 已经可以正常运行，并且可以打印Helloworld。

但是目前 `javac` 是有问题的，会报非法指令的问题：

![image](https://user-images.githubusercontent.com/19571377/148165298-3542ebc1-897e-40be-858d-e624107cb63a.png)

c查看 `java  -XX:+PrintInterpreter -version` 打印的汇编码，这里的pc值位于：

![image](https://user-images.githubusercontent.com/19571377/148165361-02eab0ff-dd90-4620-9e0b-47c029c18dc4.png)

生成汇编的cpp源文件位于：

![image](https://user-images.githubusercontent.com/19571377/148165511-0263df05-184e-41d8-bbb2-4fe180eb8c6c.png)

这里的零拓展对于rv32来说这里是多余的，注释掉以后这里的ArrayIndexOutOfBounds异常可以正常抛出了：

![image](https://user-images.githubusercontent.com/19571377/148165565-761b1cb1-be11-4aee-895e-fb1e545196cd.png)

---
### 20220106 更新

上图中的 `Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 83` 是很奇怪的，索引10明明没有超出83的范围。
这个奇怪的报错是因为只注释掉了这个零拓展指令，正确的做法是替换为 `mv` 把x11的值传递到 c_rarg2 里面。

已新建分支 https://github.com/openjdk-riscv/jdk11u/tree/rv32g-dev-javac ，报错信息合理：

![2e8254e4b4bf6d36d623c19e1ac7b45](https://user-images.githubusercontent.com/19571377/148321370-a1d3f33b-e1a7-43af-aaab-9e11041851c0.png)

**Comment by zhangxiang-plct** [comment]
根据异常抛出信息，定位到具体的抛出点
```
address TemplateInterpreterGenerator::generate_ArrayIndexOutOfBounds_handler() {
  address entry = __ pc();
  // expression stack must be empty before entering the VM if an
  // exception happened
  __ empty_expression_stack();
  // setup parameters

  // convention: expect aberrant index in register x11
  //__ zero_ext(c_rarg2, x11, 32);
  // convention: expect array in register x13
  __ mv(c_rarg1, x13);
  __ call_VM(noreg,
             CAST_FROM_FN_PTR(address,
                              InterpreterRuntime::
                              throw_ArrayIndexOutOfBoundsException),
             c_rarg1, c_rarg2);
  return entry;
}
```
由 **generate_ArrayIndexOutOfBounds_handler** 向上追溯到 **_throw_ArrayIndexOutOfBoundsException_entry**

![image](https://user-images.githubusercontent.com/84717784/148252629-9012ac97-cf17-45a8-9026-3e91e4bb67f0.png)


接着发现 **_throw_ArrayIndexOutOfBoundsException_entry** 在 **TemplateTable::index_check** 中被调用

```
void TemplateTable::index_check(Register array, Register index)
{
  // destroys x11, t0
  // check array
  __ null_check(array, arrayOopDesc::length_offset_in_bytes());
  // sign extend index for use by indexed load
  // check index
  const Register length = t0;
  __ lw(length, Address(array, arrayOopDesc::length_offset_in_bytes()));
  if (index != x11) {
    assert(x11 != array, "different registers");
    __ mv(x11, index);
  }
  Label ok;
  __ add(index, index, zr);
  __ bltu(index, length, ok);
  __ mv(x13, array);
  __ mv(t0, Interpreter::_throw_ArrayIndexOutOfBoundsException_entry);
  __ jr(t0);
  __ bind(ok);
}
```
对所有调用 **index_check** 的地方进行调试发现,是在 **TemplateTable::aaload()** 发生了错误

```
void TemplateTable::aaload()
{
  transition(itos, atos);
  __ mv(x11, x10);
  __ pop_ptr(x10);
  // x10: array
  // x11: index
  index_check(x10, x11); // leaves index in x11
  __ add(x11, x11, arrayOopDesc::base_offset_in_bytes(T_OBJECT) >> LogBytesPerHeapOop);
  __ slli(t0, x11, LogBytesPerHeapOop);
  __ add(t0, t0, x10);
  do_oop_load(_masm,
              Address(t0),
              x10,
              IS_ARRAY);
}
```

将此处的  index_check(x10, x11) 的调用注释掉，便不会产生 ArrayIndexOutOfBounds异常的抛出。


![image](https://user-images.githubusercontent.com/84717784/148252172-295c0e50-707d-4c78-9274-6ba867e5a43d.png)


具体的修改尚未完成，后续接着调试确定修改方案。

**Comment by shining1984** [comment]
根据最新的javac分支的代码 #309 ,对于只运行javac命令时候的输出：
rv32g：
![image](https://user-images.githubusercontent.com/3916635/148508334-6a5a6409-4c70-4ac4-bf2e-d0e944b48e29.png)
x86 jdk10:
![image](https://user-images.githubusercontent.com/3916635/148508407-88bd9470-97b9-4a43-b43c-2f00728dae5f.png)
可以看出，目前报的问题，发生在本该输出：
@<filename>                  Read options and filenames from file

这里的内容的时候。所以从这里出发排查javac的流程，看看是在哪里加载这块内容，且涉及到了架构相关代码。

**Comment by DingliZhang** [comment]
已在 #314 #318 中修复。
