### ISSUE TITLE
RV32G interpreterRT相关代码移植

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#32]
interpreterRT相关

src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp
src/hotspot/cpu/riscv32/interpreterRT_riscv32.hpp

**Comment by shining1984** [comment]
interpreterRT_riscv32.cpp 中涉及到了lw和sw、ld和sd等指令：

![image](https://user-images.githubusercontent.com/3916635/112451842-e6af7e80-8d90-11eb-998e-7665cd8def3c.png)

根据上图

不用修改的有：
lw
sw
fld

修改的地方：
ld->flw
sd->fsw

**Comment by shining1984** [comment]
另外，还有两处lwu的地方，lwu在规范中：

![image](https://user-images.githubusercontent.com/3916635/112454986-3c395a80-8d94-11eb-9313-e871bc84bb78.png)

![image](https://user-images.githubusercontent.com/3916635/112455247-802c5f80-8d94-11eb-8370-5459312d2670.png)

虽然lw和lwu看起来是扩展方式不同，但是在rv32g的情况下，貌似使用lw替换lwu是最好的方式，所以暂时使用这种方式。

lwu->lw

**Comment by shining1984** [comment]
所以，修改的地方一共有：
ld->flw
sd->fsw
lwu->lw

**Comment by shining1984** [comment]
#35 已经提交。

测试过程和结果如 #31 所示。

@DingliZhang 请review和验证。

**Comment by DingliZhang** [comment]
#35 已经review、验证通过，并且合并。
