### ISSUE TITLE
RV32 core模式下的jtreg测试

### ISSUE THREAD

**Issue by zifeihan** [openjdk-riscv/jdk11u#333]
在使用 jtreg 来测试 OpenJDK for RV32G版本 ，测试集使用：`jdk11u/test`下面的测试集，因为执行`jdk11u/test`下所有的测试集时间需要很久，因此先进行`/jdk11u/test/langtools`下测试集的执行，命令如下：`./jtreg -jdk:/home/zifeihan/linux-riscv32-normal-core-release/jdk  /home/zifeihan/jdk11u/test/langtools`
发生了如下报错：
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x3fd3593a, pid=229798, tid=229940
#
# JRE version: OpenJDK Runtime Environment (11.0.9) (build 11.0.9-internal+0-adhoc.zifeihan.jdk11u)
# Java VM: OpenJDK Core VM (11.0.9-internal+0-adhoc.zifeihan.jdk11u, interpreted mode, serial gc, linux-riscv32)
# Problematic frame:
# V  [libjvm.so+0x48193a]  Symbol::as_klass_external_name() const+0xe
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/zifeihan/jtreg/build/images/jtreg/bin/hs_err_pid229798.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted
```
但是相同的测试集使用 jtreg 来测试 BishengJDK 的执行情况是并没有发生如上的异常，执行的时间比较久，但是并未遇到异常。
![image](https://user-images.githubusercontent.com/16839929/150112683-3fa7348f-dc1d-41b9-8829-5a6160f1bfb2.png)

**Comment by DingliZhang** [comment]
![image](https://user-images.githubusercontent.com/19571377/150248530-2af4b8b2-82d5-4991-ac6f-d6d7046d0c0f.png)

可以加上 `-concurrency:4` 参数试试，我怀疑是默认的并发数太大导致的问题。

**Comment by zifeihan** [comment]
同上使用 -concurrency:4/8 来测试制线程大小的影响，也会有别的异常问题：
![image](https://user-images.githubusercontent.com/16839929/150270699-d6585662-82cb-4eb0-a753-5a7de85b5e76.png)

**Comment by zifeihan** [comment]
使用相同的命令对OpenJDK for RV32G进行测试，有的时候能执行成功，有的时候执行失败，目前在排查执行失败的原因：
```
zifeihan@plct-8:~/jtreg/build/images/jtreg/bin$ ./jtreg -a -ea -esa -v:fail,error,time -retain:fail,error -ignore:quiet  -jdk:/home/zifeihan/linux-riscv32-normal-core-release/jdk -concurrency:4 /home/zifeihan/jdk11u/test/langtools/jdk/javadoc/tool/modules
^@^@^@^@#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x3fd3593a, pid=1062984, tid=1063134
#
# JRE version: OpenJDK Runtime Environment (11.0.9) (build 11.0.9-internal+0-adhoc.zifeihan.jdk11u)
# Java VM: OpenJDK Core VM (11.0.9-internal+0-adhoc.zifeihan.jdk11u, interpreted mode, serial gc, linux-riscv32)
# Problematic frame:
# V  [libjvm.so+0x48193a]  Symbol::as_klass_external_name() const+0xe
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/zifeihan/jtreg/build/images/jtreg/bin/hs_err_pid1062984.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted
zifeihan@plct-8:~/jtreg/build/images/jtreg/bin$ ./jtreg -a -ea -esa -v:fail,error,time -retain:fail,error -ignore:quiet  -jdk:/home/zifeihan/linux-riscv32-normal-core-release/jdk -concurrency:4 /home/zifeihan/jdk11u/test/langtools/jdk/javadoc/tool/modules
^@^@^@^@^@^@^@--------------------------------------------------
TEST: jdk/javadoc/tool/modules/CommandLineFiles.java
  build: 0.071 seconds
  build: 35.682 seconds
  compile: 35.672 seconds
  main: 30.034 seconds
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: jdk/javadoc/tool/modules/Modules.java
  build: 0.071 seconds
  build: 0.001 seconds
  main: 67.373 seconds
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: jdk/javadoc/tool/modules/MissingSourceModules.java
  build: 0.071 seconds
  build: 35.743 seconds
  compile: 35.734 seconds
  main: 33.638 seconds
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: jdk/javadoc/tool/modules/FilterOptions.java
  build: 0.071 seconds
  build: 37.272 seconds
  compile: 37.263 seconds
  main: 39.674 seconds
TEST RESULT: Passed. Execution successful
--------------------------------------------------
^@^@TEST: jdk/javadoc/tool/modules/ReleaseOptions.java
  build: 0.002 seconds
  build: 34.567 seconds
  compile: 34.566 seconds
  main: 31.379 seconds
TEST RESULT: Passed. Execution successful
--------------------------------------------------
TEST: jdk/javadoc/tool/modules/PackageOptions.java
  build: 0.002 seconds
  build: 35.134 seconds
  compile: 35.134 seconds
  main: 37.008 seconds
TEST RESULT: Passed. Execution successful
--------------------------------------------------
^@TEST: jdk/javadoc/tool/modules/PatchModules.java
  build: 0.002 seconds
  build: 36.334 seconds
  compile: 36.334 seconds
  main: 46.977 seconds
TEST RESULT: Passed. Execution successful
--------------------------------------------------
Test results: passed: 7
^@^@^@^@^@Report written to /home/zifeihan/jtreg/build/images/jtreg/bin/JTreport/html/report.html
Results written to /home/zifeihan/jtreg/build/images/jtreg/bin/JTwork
zifeihan@plct-8:~/jtreg/build/images/jtreg/bin$ ./jtreg -a -ea -esa -v:fail,error,time -retain:fail,error -ignore:quiet  -jdk:/home/zifeihan/linux-riscv32-normal-core-release/jdk -concurrency:4 /home/zifeihan/jdk11u/test/langtools/jdk/javadoc/tool/modules
^@^@^@^@^@#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x3fd83e5c, pid=1063935, tid=1064069
#
# JRE version: OpenJDK Runtime Environment (11.0.9) (build 11.0.9-internal+0-adhoc.zifeihan.jdk11u)
# Java VM: OpenJDK Core VM (11.0.9-internal+0-adhoc.zifeihan.jdk11u, interpreted mode, serial gc, linux-riscv32)
# Problematic frame:
# V  [libjvm.so+0x4cfe5c]  Unsafe_EnsureClassInitialized0+0xe8
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/zifeihan/jtreg/build/images/jtreg/bin/hs_err_pid1063935.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted
zifeihan@plct-8:~/jtreg/build/images/jtreg/bin$
```

**Comment by zifeihan** [comment]
源码如下，该代码为执行一个 shell 并获取其PID，该PID确实应该为变化的，但是不应该是像OpenJDK for RV32G那么大的值：
```
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Method;

public class GetPID {
    public static void main(String[] args) throws IOException {

        final Process proc = Runtime.getRuntime().exec("ls ");
        try {
            try {
                Method pid = Process.class.getMethod("pid");
                System.out.println((Long) pid.invoke(proc));;
            } catch (NoSuchMethodException ignore) {
                // This exception is expected on pre-JDK 9,
                // try a fallback method that only works on Unix platforms
                System.out.println(getProcessIdPreJdk9(proc));;
            }
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException(e);
        }
    }

    private static long getProcessIdPreJdk9(Process proc)
        throws IllegalAccessException, NoSuchFieldException {
        if (proc.getClass().getName().equals("java.lang.UNIXProcess")) {
            int pid;
            Field f = proc.getClass().getDeclaredField("pid");
            boolean oldValue = f.isAccessible();
            try {
                f.setAccessible(true);
                pid = f.getInt(proc);
            } finally {
                f.setAccessible(oldValue);
            }
            return pid;
        }
        return 0;
    }
}
```
OpenJDK for RV32G执行结果如下：
![image](https://user-images.githubusercontent.com/16839929/150902069-d706d9be-1cf8-4280-abd4-ad568ee17a1a.png)
BishengJDK执行结果如下：
![image](https://user-images.githubusercontent.com/16839929/150902725-03e4a95e-4b8e-4fd1-b152-d6b5994dc846.png)


在调试过程中，如下函数可能栈帧有问题，目前正在排查该问题：
![image](https://user-images.githubusercontent.com/16839929/150901897-72d86143-8922-471e-bd69-158c49d17c09.png)

**Comment by zifeihan** [comment]
测试用例如：
```
import java.lang.reflect.Method;

/**
 * Test reflect invoke
 */
public class TestReflectInvoke {
    public static void main(String[] args)  {
        try {
            TestReflectInvoke.test();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public static void test() {
        try {
            Method pid = TestReflectInvoke.class.getMethod("aa");
            final Long result = (Long)pid.invoke(null);
            System.out.println(result);
            Assert.isTrue(result==99999,"assert result error");
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public static long aa() {
        return 99999;
    }
}

```
修复前结果如下：
![image](https://user-images.githubusercontent.com/16839929/151690332-0a4edd2b-fb3d-471d-bd97-d7cee0d8e80e.png)

PR: https://github.com/openjdk-riscv/jdk11u/pull/334 修复后结果如下：
![image](https://user-images.githubusercontent.com/16839929/151690253-5f710f68-dae8-4eb0-82c5-906fbcb1e56d.png)

**Comment by zifeihan** [comment]
提交PR后：https://github.com/openjdk-riscv/jdk11u/pull/334
testcase-jdk11u-rv32g 测试集运行正常：
![image](https://user-images.githubusercontent.com/16839929/153787090-14b75dd2-c772-4e13-aad4-1b511240d2ec.png)

**Comment by zifeihan** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/16839929/157480131-fed6cf1f-104b-496b-8b96-18300564117b.png">
目前 test/langtools 可以正常进行测试了（不会发生crash），测试报告如附件。

[JTreport.tar.gz](https://github.com/openjdk-riscv/jdk11u/files/8216156/JTreport.tar.gz)

**Comment by zifeihan** [comment]
jtreg 测试 langtools 命令：`nohup ./jtreg -a -ea -esa -v:fail,error,time -retain:fail,error -ignore:quiet  -jdk:/home/zifeihan/jdk11u/build/linux-riscv32-normal-core-slowdebug/jdk -concurrency:4 /home/zifeihan/jdk11u/test/langtools/ > dddd.log &`

**Comment by zifeihan** [comment]
在PR：https://github.com/openjdk-riscv/jdk11u/pull/351 修复后，jtreg执行就不会发生 crash。目前可以正常通过 test/langtools 测试集。

**Comment by zifeihan** [comment]
3.11 更新 test/langtools 测试结果，全部可以正常执行结束，未发生crash。
[JTreport.tar.gz](https://github.com/openjdk-riscv/jdk11u/files/8228284/JTreport.tar.gz)

<img width="555" alt="image" src="https://user-images.githubusercontent.com/16839929/157784893-7920110b-16db-49d1-a5f0-584bf9736c36.png">

**Comment by zifeihan** [comment]
test/jdk 测试结果，全部可以正常执行结束，未发生crash。
[JTreport-jdk.zip](https://github.com/openjdk-riscv/jdk11u/files/8245640/JTreport-jdk.zip)
<img width="525" alt="image" src="https://user-images.githubusercontent.com/16839929/158192039-cc01e206-4a22-4423-8e25-16082b566f99.png">

**Comment by zifeihan** [comment]
test/nashorn 测试结果，全部可以正常执行结束，未发生crash。
[JTreport-jaxp.zip](https://github.com/openjdk-riscv/jdk11u/files/8249125/JTreport-jaxp.zip)
<img width="516" alt="image" src="https://user-images.githubusercontent.com/16839929/158279934-ed47e501-675e-4e52-bae5-3f03bed688ec.png">

**Comment by zifeihan** [comment]
目前测试下来，jtreg 下相关的 java程序测试均可以执行，虚拟机并未发生crash，但是在执行过程中还有一些java层面异常，或者执行超时的情况，需要进一步排查。

**Comment by zifeihan** [comment]
在使用Openjdk for RV32G 进行 jtreg 测试 test/jdk 测试集时，发现 /home/zifeihan/jdk11u/test/jdk/java/time/tck/java/time/TCKMonth.java 测试不能通过：
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/16839929/159654460-2068a170-89a0-467b-bd5b-f0e0764647b2.png">

于是进行问题排查，发现在 src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp 传递Long类型参数时，未能兼容32位的处理器。参考arm32 进行修复，PR：https://github.com/openjdk-riscv/jdk11u/pull/356 ， 修复后，/home/zifeihan/jdk11u/test/jdk/java/time/tck/java/time/TCKMonth.java 测试用例可以正常通过。
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/16839929/159657608-3e786fa3-6395-4910-b9f6-71af696dbc48.png">

bishengJDK 测试结果：
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/16839929/159658546-04a553c7-2c7e-4fda-962d-b0a24c2bc2d7.png">


若是还未进行搭建jtreg测试环境，我在 [testcase-jdk11u-rv32g](https://github.com/openjdk-riscv/testcase-jdk11u-rv32g) 的maven分支上，新增了一个简化的测试用例来测试 src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp 传递Long类型参数时，未能兼容32位的处理器 这种问题的测试用例，可以使用该测试用例进行调试复现。参考：https://github.com/openjdk-riscv/testcase-jdk11u-rv32g/blob/maven/src/test/java/cn/ac/iscas/openjdk/TestReflectInvokeMethod.java

**Comment by zifeihan** [comment]
在使用Openjdk for RV32G 进行 jtreg 测试 test/jdk 测试集时，发现 test/jdk/javax/management/remote/mandatory/connection/MultiThreadDeadLockTest.java 测试不能通过
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/16839929/160076911-b6344573-2e52-41ff-bd53-3410a75ba9a8.png">
于是进行问题排查，发现在 src/hotspot/cpu/riscv32/interp_masm_riscv32.cpp:remove_activation函数中，该函数是处理字节码lreturn之类的逻辑，也会进行移除锁对象逻辑，因为在这里使用的是x11作为锁对象，有可能造成将原本的x11:x10 中的x11覆盖，从而导致数据错误。修复PR：https://github.com/openjdk-riscv/jdk11u/pull/362 ， 修复后，test/jdk/javax/management/remote/mandatory/connection/MultiThreadDeadLockTest.java 测试用例可以正常通过
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16839929/160078400-4a59c724-5280-4bda-b630-8b13556da187.png">


若是还未进行搭建jtreg测试环境，我在 [testcase-jdk11u-rv32g](https://github.com/openjdk-riscv/testcase-jdk11u-rv32g) 的maven分支上，新增了一个简化的测试用例来测试用例，可以使用该测试用例进行调试复现。参考：https://github.com/openjdk-riscv/testcase-jdk11u-rv32g/blob/maven/src/test/java/cn/ac/iscas/openjdk/MultiThreadDeadLockTest.java

**Comment by zifeihan** [comment]
BishengJDK jtreg测试报告如下：[jtreg-64.zip](https://github.com/openjdk-riscv/jdk11u/files/8388442/jtreg-64.zip)
jaxp 成功率：19/438=4%
jdk 成功率：6706/9835=68%
langtools 成功率：3687/3943=94%
nashorn 成功率：35/36=97%

**Comment by zifeihan** [comment]
OpenJDK for RV32G jtreg测试报告如下：[jtreg-32.zip](https://github.com/openjdk-riscv/jdk11u/files/8388482/jtreg-32.zip)
jaxp 成功率：18/438=4%
jdk 成功率：6735/9835=68%
langtools 成功率：3687/3943=93%
nashorn 成功率：35/36=94%

**Comment by zifeihan** [comment]
在使用Openjdk for RV32G 进行 jtreg 测试 test/jdk 测试集时，发现 src/jdk/nashorn/internal/runtime/doubleconv/test/IeeeDoubleTest.java 测试不能通过：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16839929/162152811-9bdcf33f-a803-421a-9930-6b0aab05783c.png">

于是进行问题排查，发现在 src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp 传递Double类型参数时，未能兼容32位。参考arm32 进行修复，PR：https://github.com/openjdk-riscv/jdk11u/pull/369 ， 修复后，src/jdk/nashorn/internal/runtime/doubleconv/test/IeeeDoubleTest.java 测试用例可以正常通过。
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16839929/162154035-1a051c2d-205c-44b7-b970-8fc1196234f3.png">

若是还未进行搭建jtreg测试环境，我在 [testcase-jdk11u-rv32g](https://github.com/openjdk-riscv/testcase-jdk11u-rv32g) 的maven分支上，新增了一个简化的测试用例来测试 src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp 传递Double类型参数时，未能兼容32位的处理器 这种问题的测试用例，可以使用该测试用例进行调试复现。参考：https://github.com/openjdk-riscv/testcase-jdk11u-rv32g/blob/maven/src/test/java/cn/ac/iscas/openjdk/IeeeDoubleTest.java
