### ISSUE TITLE
make问题汇总

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#349]
之前讨论过的两个issue：
[make run-test-tier1报错](https://github.com/openjdk-riscv/jdk11u/issues/22)
[make install报错问题](https://github.com/openjdk-riscv/jdk11u/issues/171)

**Comment by DingliZhang** [comment]
在review PR #348的时候：https://github.com/openjdk-riscv/jdk11u/issues/342#issuecomment-1061364299
使用 `make` 和 `make images` 构建出来的jdk运行结果出现了差异，使用 `make` 构建的报错信息：
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/19571377/157191228-de5bd176-2de7-46ce-bb51-a30ecf9b6f5f.png">

**Comment by shining1984** [comment]
release版本的make和make images的差别已经解决了。见：https://github.com/openjdk-riscv/jdk11u/pull/350

**Comment by DingliZhang** [comment]
在core模式下进行分析：
commit info
```
commit ad14e9004c1dc6d91f7d7b99554c391e7df5dee3 (HEAD -> rv32g-dev, upstream/rv32g-dev)
Merge: 506a9502fd bbd830cf0f
Author: zhangxiang-plct <zhangxiang@iscas.ac.cn>
Date:   Fri Mar 25 19:40:15 2022 +0800

    Merge pull request #362 from zifeihan/fix_synchronized
    
    Fix x11 registers not saving correctly when using synchronized
```

打上以下patch：
```diff
diff --git a/src/hotspot/share/runtime/thread.inline.hpp b/src/hotspot/share/runtime/thread.inline.hpp
index 4a48fe299f..c87f7d10fd 100644
--- a/src/hotspot/share/runtime/thread.inline.hpp
+++ b/src/hotspot/share/runtime/thread.inline.hpp
@@ -126,6 +126,8 @@ inline JavaThreadState JavaThread::thread_state() const    {
 }
 
 inline void JavaThread::set_thread_state(JavaThreadState s) {
+  assert(current_or_null() == NULL || current_or_null() == this,
+        "state change should only be called by the current thread");
   OrderAccess::release_store((volatile jint*)&_thread_state, (jint)s);
 }
 #endif
```

在打上patch之前，只有slowdebug版本在images时会出现 https://github.com/openjdk-riscv/jdk11u/issues/349#issuecomment-1061500005 中的报错信息：
| operation                  | release | slowdebug |
| :-------------------- | :------ | :-------- |
| make                  | success | success   |
| run after make        | success | success   |
| make images           | success | fail      |
| run after make images | success | N/A       |

而打上patch之后，slowdebug在make之后的运行也会出现报错：
| operation                  | release | slowdebug |
| :-------------------- | :------ | :-------- |
| make                  | success | success   |
| run after make        | success | fail   |
| make images           | success | fail      |
| run after make images | success | N/A       |
报错信息：
```
# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/thread.inline.hpp:129
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/home/dingli/jdk11u/src/hotspot/share/runtime/thread.inline.hpp:129), pid=2197834, tid=2197836
#  assert(current_or_null() == __null || current_or_null() == this) failed: state change should only be called by the current thread .
#
# JRE version:  (11.0.9) (slowdebug build )
# Java VM: OpenJDK Core VM (slowdebug 11.0.9-internal+0-adhoc.dingli.jdk11u, interpreted mode, serial gc, linux-riscv32)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/dingli/jdk11u/hs_err_pid2197834.log
#
#
Current thread is 2197836
Dumping core ...
```

正好就是patch中在 `thread.inline.hpp:129` 中添加的assert。

所以我们可以发现两个问题：
1. make images和make的宏定义不同 （从打上patch之后，slowdebug在make之后的运行也会出现报错可以得出）
2. slowdebug版本的断言是有问题的

**Comment by DingliZhang** [comment]
在core模式下进行分析：
commit info
```
commit ad14e9004c1dc6d91f7d7b99554c391e7df5dee3 (HEAD -> rv32g-dev, upstream/rv32g-dev)
Merge: 506a9502fd bbd830cf0f
Author: zhangxiang-plct <zhangxiang@iscas.ac.cn>
Date:   Fri Mar 25 19:40:15 2022 +0800

    Merge pull request #362 from zifeihan/fix_synchronized
    
    Fix x11 registers not saving correctly when using synchronized
```


打上以下patch：
```diff
diff --git a/src/hotspot/share/runtime/thread.inline.hpp b/src/hotspot/share/runtime/thread.inline.hpp
index 4a48fe299f..cfb10c5c23 100644
--- a/src/hotspot/share/runtime/thread.inline.hpp
+++ b/src/hotspot/share/runtime/thread.inline.hpp
@@ -126,6 +126,10 @@ inline JavaThreadState JavaThread::thread_state() const    {
 }
 
 inline void JavaThread::set_thread_state(JavaThreadState s) {
+  if(current_or_null() == NULL || current_or_null() == this){
+  }else{
+    warning("fasle!");
+  }
   OrderAccess::release_store((volatile jint*)&_thread_state, (jint)s);
 }
 #endif
```

运行结果：
```
$ /home/dingli/qemu-5.2.0-rv32/bin/qemu-riscv32 -L /opt/riscv32/sysroot ~/jdk11u/build/linux-riscv32-normal-core-release/jdk/bin/java -version
OpenJDK Core VM warning: fasle!
OpenJDK Core VM warning: fasle!
OpenJDK Core VM warning: fasle!
OpenJDK Core VM warning: fasle!
OpenJDK Core VM warning: fasle!
openjdk version "11.0.9-internal" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.dingli.jdk11u)
OpenJDK Core VM (build 11.0.9-internal+0-adhoc.dingli.jdk11u, interpreted mode)
```

可以看到其实release版本也是不满足slowdebug中报错的断言的，但是由于 `ASSERT` 这个宏在release版本下是未定义的，所以即使是 `assert(false,"false!");` 这样的断言在release版本中也是不会报错的。

**Comment by zhangxiang-plct** [comment]
对这个断言进行分析：
```
inline void JavaThread::set_thread_state(JavaThreadState s) {
  assert(current_or_null() == NULL || current_or_null() == this,
         "state change should only be called by the current thread");
#if defined(PPC64) || defined(AARCH64) || defined(RISCV32)
  OrderAccess::release_store((volatile jint*)&_thread_state, (jint)s);
#else
  _thread_state = s;
#endif
}
```
此处的断言为false：即表示current_or_null（）！=NULL && current_or_null()!=this

```
inline Thread* Thread::current_or_null() {
#ifndef USE_LIBRARY_BASED_TLS_ONLY
  return _thr_current;
#else
  if (ThreadLocalStorage::is_initialized()) {
    return ThreadLocalStorage::thread();
  }
  return NULL;
#endif
}
```
那么也就表示 ThreadLocalStorage::thread()!=NULL&&ThreadLocalStorage::thread()!=this

```
Thread* ThreadLocalStorage::thread() {
  // If this assert fails we will get a recursive assertion failure
  // and not see the actual error message or get a hs_err file.
  // Which most likely indicates we have taken an error path early in
  // the initialization process, which is using Thread::current without
  // checking TLS is initialized - see java.cpp vm_exit
  assert(_initialized, "TLS not initialized yet!");
  return (Thread*) pthread_getspecific(_thread_key); // may be NULL
}
```
在 ThreadLocalStorage::thread() 中加打印，发现

![image](https://user-images.githubusercontent.com/84717784/161082721-301f011b-37ce-41f5-8976-b12471f3ead0.png)

**Comment by DingliZhang** [comment]
调试断言：
```
assert(current_or_null() == NULL || current_or_null() == this,
         "state change should only be called by the current thread");
```

这个断言在native编译x86版本的jdk的时候就会报错，执行命令：
```
$ bash configure --disable-warnings-as-errors --with-debug-level=slowdebug --with-native-debug-symbols=internal
$ make JOBS=$(nproc)
```
这个断言最早是在 https://github.com/openjdk/jdk11u/commit/2e59cd82d77c553932bad485e132214d64fcfbc8 这个commit里添加的，对应的的版本号为11.0.10，而目前我们repo中的版本号为11.0.9，代码差异是比较大的，如果在原始的11.0.9代码中加上这个断言的话，编译x86版本的jdk也是会报错的。

升级版本在目前的工作中优先级是比较低的，所以我们选择回退代码来解决这个问题。
rv32g-dev分支：#365
rv32g-dev-c2分支：#364
提交后native编译x86版本jdk以及rv32g交叉编译的make images都不会报错了。

**Comment by DingliZhang** [comment]
make images/make install会比make做更多的事情，而且make出的jdk镜像是不能直接拷贝到其他地方运行的。
在 `make/Main.gmk`，可以看到如下注释：

  # Jmods cannot be created until we have the jmod tool ready to run. During
  # a normal build we run it from the exploded image, but when cross compiling
  # it's run from the buildjdk, which is either created at build time or user
  # supplied.

在 https://github.com/openjdk-riscv/jdk11u/blob/master/doc/building.md#boot-jdk-and-build-jdk 可以看到，当交叉编译的时候，会生成一个build-jdk（经测试make images/make install 会生成，而make不会生成），这个build-jdk是能在构建平台上运行，而不是可以在目标系统上运行的，所以会出现make images/make install与make宏定义不同的情况。
