### ISSUE TITLE
RV32G register相关代码移植

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#37]
register相关

1. src/hotspot/cpu/riscv32/registerMap_riscv32.hpp
2. src/hotspot/cpu/riscv32/register_defitions_riscv32.cpp
3. src/hotspot/cpu/riscv32/register_riscv32.cpp
4. src/hotspot/cpu/riscv32/register_riscv32.hpp

**Comment by DingliZhang** [comment]
这四个文件是关于寄存器的定义、声明、名称以及一些构建和访存器函数，还有查找寄存器的映射等。由于RV64与RV32寄存器的个数及名称都是相同的，在此模块的文件中不含有与位宽相关的代码，因此在移植时只需要修改"64"的文本及注释即可。

**Comment by DingliZhang** [comment]
已经提交PR #42 
编译和结果参考 issue #34 

@shining1984 请帮忙review和验证。

**Comment by shining1984** [comment]
已经review 和验证。
PR #42  已经合并。
