### ISSUE TITLE
fld/flw、fsd/fsw的排查

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#403]
RV32的F扩展的寄存器是32位的，D扩展的寄存器是64位的。
这里会涉及到存取的时候，具体使用的是fld/flw、fsd/fsw的问题，同时还涉及到了地址的偏移问题。
如果是float，那么按照32位应该使用flw/fsw，偏移是wordsize；如果是double，那么应该使用fld/fsd，偏移量应该是2 * wordsize。
还会涉及到对于不明类型的浮点数，如果按double处理的话，那么存取应该一致。

**Comment by shining1984** [comment]
riscv32.ad中的fld/flw、fsd/fsw未发现明显问题，都是严格根据float和double的情况在使用。

**Comment by shining1984** [comment]
涉及到的文件：
1. gc/shenandoah/shenandoahBarrierSetAssembler_riscv32.cpp
2. gc/shared/barrierSetAssembler_riscv32.cpp
3.  assembler_riscv32.hpp
4.  assembler_riscv32.cpp
5.  interp_masm_riscv32.cpp
6. interpreterRT_riscv32.cpp
7. jniFastGetField_riscv32.cpp
8. macroAssembler_riscv32.hpp
9.  macroAssembler_riscv32.cpp
10.  riscv32-asmtest
11. riscv32.ad
12. sharedRuntime_riscv32.cpp
13. stubGenerator_riscv32.cpp
14. templateInterpreterGenerator_riscv32.cpp
15. templateTable_riscv32.cpp
---------------------------------------------

riscv32.ad中的fld/flw、fsd/fsw未发现明显问题，都是严格根据float和double的情况在使用。

**Comment by shining1984** [comment]
排查记录：
1. 
2. 
3. 
4. 
5. 
6. 
7. 
8. 
9. 
10. 
11. riscv32.ad中的fld/flw、fsd/fsw未发现明显问题，都是严格根据float和double的情况在使用。

**Comment by shining1984** [comment]
1. gc/shenandoah/shenandoahBarrierSetAssembler_riscv32.cpp

在ShenandoahBarrierSetAssembler::storeval_barrier()中，这里的fld和fsd都各使用了一次，但是对应的wordsize本来就是乘以2了。那就意味着在RV64下边，本来是准备了两个64位的内容，但是fld/fsd只拿了一个。怀疑这里是不合理的。

跟踪rv64的代码，最新的内容，storeval_barrier函数已经更名为iu_barrier函数，其内容也改为对satb_write_barrier_pr函数等的调用。所以，参照最新代码，对RV32目前的storeval_barrier()进行更新。

**Comment by zhangxiang-plct** [comment]
12sharedRuntime_riscv32.cpp中的两处关于fsd以及fld的处理，也需要对wordsize做出修改：
```C++
void SharedRuntime::save_native_result(MacroAssembler *masm, BasicType ret_type, int frame_slots) {
  assert_cond(masm != NULL);
  // We always ignore the frame_slots arg and just use the space just below frame pointer
  // which by this time is free to use
  switch (ret_type) {
  case T_FLOAT:
    __ fsw(f10, Address(fp, -wordSize));
    break;
  case T_DOUBLE:
    __ fsd(f10, Address(fp, -wordSize));
    break;
  case T_VOID:  break;
  default: {
    __ sw(x10, Address(fp, -wordSize));
    }
  }
}
```
```C++
void SharedRuntime::restore_native_result(MacroAssembler *masm, BasicType ret_type, int frame_slots) {
  assert_cond(masm != NULL);
  // We always ignore the frame_slots arg and just use the space just below frame pointer
  // which by this time is free to use
  switch (ret_type) {
  case T_FLOAT:
    __ flw(f10, Address(fp, -wordSize));
    break;
  case T_DOUBLE:
    __ fld(f10, Address(fp, -wordSize));
    break;
  case T_VOID:  break;
  default: {
    __ lw(x10, Address(fp, -wordSize));
    }
  }
}
```

**Comment by shining1984** [comment]
目前发现需要修改的地方有：
9. macroAssembler_riscv32.cpp 中的fld、fsd各有两处，wordsize的问题需要改进。
12.sharedRuntime_riscv32.cpp中的两处关于fsd以及fld的处理，也需要对wordsize做出修改
14. templateInterpreterGenerator_riscv32.cpp 中fld较多，需要逐个考虑其偏移量问题。

**Comment by shining1984** [comment]
9. macroAssembler_riscv32.cpp 中的fld、fsd各有两处，wordsize的问题需要改进。
12.sharedRuntime_riscv32.cpp中的两处关于fsd以及fld的处理，也需要对wordsize做出修改
----------------------------------------------------------------------
上述文件的修改已经提交到：https://github.com/openjdk-riscv/jdk11u/pull/407

对当前运行结果并未有影响。

**Comment by shining1984** [comment]
templateInterpreterGenerator_riscv32.cpp 中关于fld相关内容的修改：

```
diff --git a/src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp b/src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
index 4aa0ada6e5..c3acbec4b5 100644
--- a/src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
+++ b/src/hotspot/cpu/riscv32/templateInterpreterGenerator_riscv32.cpp
@@ -72,14 +72,14 @@ int TemplateInterpreter::InterpreterCodeSize = 256 * 1024;
 address TemplateInterpreterGenerator::generate_slow_signature_handler() {
   address entry = __ pc();
 
-  __ andi(esp, esp, -8);
+  __ andi(esp, esp, -16);
   __ mv(c_rarg3, esp);
   // xmethod
   // xlocals
   // c_rarg3: first stack arg - wordSize
   // adjust sp
 
-  __ addi(sp, c_rarg3, -18 * wordSize);
+  __ addi(sp, c_rarg3, -27 * wordSize);
   __ addi(sp, sp, -2 * wordSize);
   __ sw(lr, Address(sp, 0));
 
@@ -111,15 +111,7 @@ address TemplateInterpreterGenerator::generate_slow_signature_handler() {
 
   for (int i = 0; i < Argument::n_float_register_parameters_c; i++) {
     const FloatRegister r = g_FPArgReg[i];
-    Label d, done;
-
-    __ andi(t0, c_rarg3, 1UL << i);
-    __ bnez(t0, d);
-    __ flw(r, Address(sp, (10 + i) * wordSize));
-    __ j(done);
-    __ bind(d);
-    __ fld(r, Address(sp, (10 + i) * wordSize));
-    __ bind(done);
+    __ fld(r, Address(sp, (10 + 2 * i) * wordSize));
   }
 
   // c_rarg0 contains the result from the call of
@@ -130,7 +122,7 @@ address TemplateInterpreterGenerator::generate_slow_signature_handler() {
     __ lw(rm, Address(sp, i * wordSize));
   }
 
-  __ addi(sp, sp, 18 * wordSize);
+  __ addi(sp, sp, 27 * wordSize);
   __ ret();
 
   return entry;
```
