### ISSUE TITLE
调研OpenJDK 8的RISC-V支持状况

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#408]
1、调研OpenJDK 8的RISC-V支持状况；
2、如果没有支持RV64的ZERO解释器，则需要修改出支持版本；如果已经有支持的了，需要给出详细的链接和验证结果。

**Comment by zhangxiang-plct** [comment]
1、[fedora支持rv64](http://fedora.riscv.rocks/koji/buildinfo?buildID=195805)

![image](https://user-images.githubusercontent.com/84717784/173297615-6d4b79ae-e838-4d65-ae6f-6a524018b302.png)

![image](https://user-images.githubusercontent.com/84717784/173297648-dc43bc62-1478-409d-9376-c2a24a56b751.png)

**Comment by zhangxiang-plct** [comment]
**验证过程**
基于K9环境下进行验证

1、下载bootjdk--jdk7的源码
`wget https://download.java.net/openjdk/jdk7u75/ri/jdk_ri-7u75-b13-linux-x64-18_dec_2014.tar.gz`
解压
`tar -xvf jdk_ri-7u75-b13-linux-x64-18_dec_2014.tar.gz` 

2、下载jdk8源码：
[fedora实现jdk8支持rv64:](http://fedora.riscv.rocks/koji/buildinfo?buildID=195805)
![image](https://user-images.githubusercontent.com/84717784/173345132-14f403bd-5e5a-4f2a-919e-b1565bcf650d.png)

`git clone http://fedora.riscv.rocks:3000/rpms/java-1.8.0-openjdk.git`

3、下载rpm包
`wget http://fedora.riscv.rocks/kojifiles/packages/java-1.8.0-openjdk/1.8.0.292.b10/1.1.riscv64.fc33/src/java-1.8.0-openjdk-1.8.0.292.b10-1.1.riscv64.fc33.src.rpm`

4、解压rpm包

`rpm2cpio java-1.8.0-openjdk-1.8.0.292.b10-1.1.riscv64.fc33.src.rpm | cpio -div`

5、解压源码包
在 “java-1.8.0-openjdk”目录下：
`tar -xvf aarch64-port-jdk8u-shenandoah-aarch64-shenandoah-jdk8u292-b10-4curve.tar.xz`
解压后获得“openjdk”目录

6、打上patch
进入“openjdk”下
`git apply java-1.8.0-riscv-1.patch`

7、执行：
`bash common/autoconf/autogen.sh`

8、构建
```
bash configure \
--with-boot-jdk=/home/zhangxiang/jdk-7/java-se-7u75-ri \
--openjdk-target=riscv64-unknown-linux-gnu \
--with-sysroot=/opt/riscv64/sysroot \
--with-debug-level=slowdebug \
--with-native-debug-symbols=internal \
--with-jvm-variants=zero \
--with-jvm-interpreter=cpp \
--x-includes=/opt/riscv64/sysroot/usr/include\X11\extension \
--x-libraries=/opt/riscv64/sysroot/usr/lib \
--with-cups=/opt/riscv64/sysroot/usr/include/cups \
--with-freetype-include=/opt/riscv64/sysroot/usr/include/freetype2 \
--with-freetype-lib=/opt/riscv64/sysroot/usr/lib 
```

**Comment by zhangxiang-plct** [comment]
构建成功后，make会报错：
![image](https://user-images.githubusercontent.com/84717784/173346584-405b20ed-1191-4a16-88ea-e4f5bb6089c1.png)

目前暂未解决报错问题，仍在排查中

**Comment by zhangxiang-plct** [comment]
> 使用上述命令configure的话，gcc与g++无法正确识别： <img alt="image" width="1510" src="https://user-images.githubusercontent.com/19571377/178707289-13ae5574-d801-4087-b314-ba56dcae1904.png">
> 
> 更新一下编译命令：
> 
> ```shell
> CC=/opt/riscv64/bin/riscv64-unknown-linux-gnu-gcc \
> CXX=/opt/riscv64/bin/riscv64-unknown-linux-gnu-g++ \
> bash configure \
> --with-sysroot=/opt/riscv64/sysroot \
> --openjdk-target=riscv64-unknown-linux-gnu \
> --with-boot-jdk=/home/dingli/zulu7.52.0.11-ca-jdk7.0.332-linux_x64 \
> --with-jvm-variants=zero \
> --with-debug-level=release \
> --with-native-debug-symbols=none \
> --x-includes=/opt/riscv64/sysroot/usr/include/X11/extension \
> --x-libraries=/opt/riscv64/sysroot/usr/lib \
> --with-cups=/opt/riscv64/sysroot/usr/include/cups \
> --with-freetype-include=/opt/riscv64/sysroot/usr/include/freetype2 \
> --with-freetype-lib=/opt/riscv64/sysroot/usr/lib \
> --with-extra-cflags="-Wno-error" 
> ```
> 
> 即可编译成功： <img alt="image" width="772" src="https://user-images.githubusercontent.com/19571377/178706953-122d7bf2-eb09-44d4-b800-a1f9d3ec38d1.png">

![image](https://user-images.githubusercontent.com/84717784/178713316-ae286055-7058-44b2-8d39-c47762273e14.png)
验证通过

**Comment by shining1984** [comment]
该项目已经成为独立项目。
