### ISSUE TITLE
rv32g jni相关的移植

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#49]
jni相关

src/hotspot/cpu/riscv32/jniFastGetField_riscv32.cpp
src/hotspot/cpu/riscv32/jniTypes_riscv32.hpp

**Comment by shining1984** [comment]
jniFastGetField_riscv32.cpp修改的指令：
ld->flwf

**Comment by shining1984** [comment]
jniTypes_riscv32.hpp修改了文件名和文本中的64.
jniFastGetField_riscv32.cpp修改了文件命中的64.

**Comment by shining1984** [comment]
PR #50 已经提交。
验证过程和结果如 #44 所示。

@DingliZhang 请review和验证。

**Comment by DingliZhang** [comment]
> ld->flwf

这里应该是flw，代码中是正确的

**Comment by shining1984** [comment]
> > ld->flwf
> 
> 这里应该是flw，代码中是正确的

是的，应该是flw。笔误。

**Comment by DingliZhang** [comment]
已经review和验证。

#50 已经合并。
