### ISSUE TITLE
rv32g nativeInst相关的移植

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#54]
nativeInst相关

src/hotspot/cpu/riscv32/nativeInst_riscv32.cpp
src/hotspot/cpu/riscv32/nativeInst_riscv32.hpp

**Comment by shining1984** [comment]
nativeInst_riscv32.hpp和riscv64版本比起来：

1、修改了文件名及其涉及的宏中的64到32；

2、注释掉了check_li64_data_dependency函数，目前觉得没有用，等以后运行起来调试的时候做确认；

3、注释掉了is_li64_at函数的声明；

4、注释掉了类NativeMoveRegMem的实现，这个类在RISCV64中就没有使用，所以这里注释掉；

5、将代码中五处enum RISCV64specific_constants中的64改为32；

nativeInst_riscv32.cpp和riscv64版本比起来：

1、修改了对应头文件中的64；

2、注释掉了is_li64_at函数的实现；

3、修改输出信息中的riscv64为riscv32;

**Comment by shining1984** [comment]
PR #58 已经提交，验证过程和结果如 #44 所示。
@DingliZhang 请review和验证。

**Comment by DingliZhang** [comment]
> 4、注释掉了类NativeMoveRegMem的实现，这个类在RISCV64中就没有使用，所以这里注释掉；

这里笔误了，应该是NativeMovRegMem

**Comment by DingliZhang** [comment]
PR #58 ，已经review和验证，现已合并。

**Comment by shining1984** [comment]
> > 4、注释掉了类NativeMoveRegMem的实现，这个类在RISCV64中就没有使用，所以这里注释掉；
> 
> 这里笔误了，应该是NativeMovRegMem

收到。
