### ISSUE TITLE
rv32g 宏汇编器的相关内容移植

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#70]
宏汇编器相关内容

src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp
src/hotspot/cpu/riscv32/macroAssembler_riscv32.inline.hpp

**Comment by shining1984** [comment]
src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp 中的修改：

1、ld->lw
2、sd->sw
3、64位相关的操作删除，只保留32位的操作（ifdef COMPILER2）
4、删除grev()，add_memory_int64()；

**Comment by shining1984** [comment]
src/hotspot/cpu/riscv32/macroAssembler_riscv32.inline.hpp
只修改了头文件以及相关的define

**Comment by shining1984** [comment]
src/hotspot/cpu/riscv32/macroAssembler_riscv32.cpp

1、删除grev()，add_memory_int64()实现；
2、lwu->lw ld->lw

**Comment by shining1984** [comment]
PR #77 

bash configure --with-boot-jdk=/home/shining/jdk-10 --openjdk-target=riscv32-unknown-linux-gnu --with-sysroot=/home/shining/riscv32/sysroot --disable-warnings-as-errors --with-debug-level=fastdebug --with-native-debug-symbols=internal --with-jvm-variants=core --prefix=$PWD/fastdebug_32_core

make -j

Building target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug'
Creating support/modules_libs/java.base/server/libjvm.so from 2 file(s)
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/gc/epsilon/epsilonBarrierSet.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/gc/shared/barrierSetConfig.inline.hpp:34,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/access.inline.hpp:29,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/oop.inline.hpp:30,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/markOop.inline.hpp:30,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:147:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/gc/shared/barrierSetAssembler.hpp:30:1: fatal error: gc/shared/barrierSetAssembler_riscv32.hpp: No such file or directory
   30 | #include CPU_HEADER(gc/shared/barrierSetAssembler)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/precompiled/precompiled.hpp.gch] Error 1
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/precompiled/precompiled.hpp.gch' failed
make[2]: *** [hotspot-core-libs] Error 2
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed

ERROR: Build failed for target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-core_libjvm_objs_precompiled_precompiled.hpp.gch:
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/gc/epsilon/epsilonBarrierSet.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/gc/shared/barrierSetConfig.inline.hpp:34,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/access.inline.hpp:29,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/oop.inline.hpp:30,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/markOop.inline.hpp:30,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:147:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/gc/shared/barrierSetAssembler.hpp:30:1: fatal error: gc/shared/barrierSetAssembler_riscv32.hpp: No such file or directory
   30 | #include CPU_HEADER(gc/shared/barrierSetAssembler)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

* All command lines available in /home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/make-support/failure-logs.
=== End of repeated output ===

=== Make failed targets repeated here ===
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/precompiled/precompiled.hpp.gch' failed
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed
=== End of repeated output ===

Hint: Try searching the build log for the name of the first failed target.
Hint: See doc/building.html#troubleshooting for assistance.

/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:300: recipe for target 'main' failed
make[1]: *** [main] Error 2
/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:186: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by shining1984** [comment]
@DingliZhang 请帮忙review和验证。

**Comment by DingliZhang** [comment]
已经review并且合并。
