### ISSUE TITLE
反汇编器相关内容记录

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#71]
反汇编器的相关代码：
1、src/hotspot/share/compiler/disassembler.hpp
2、src/hotspot/share/compiler/disassembler.cpp
3、src/hotspot/cpu/riscv32/disassembler_riscv32.hpp

其中，disassembler_riscv32.hpp虽然是硬件平台相关的，但是没有实质性的内容。反汇编器的内容主要位于src/utils/hsdis目录中，disassembler.cpp中也是调用hsdis相关的库。

hsdis作为一个插件，它需要单独编译，并且依赖于binutils。所以，在进行riscv32的反汇编器移植的时候，该目录也需要进行移植，添加riscv32相关的内容。

其编译过程可以参考BishengJDK的构建过程：https://github.com/openjdk-riscv/bishengjdk-11-mirror/blob/risc-v/BUILDING.md

**Comment by shining1984** [comment]
反汇编器的代码并未和汇编器和宏汇编器相关代码放在一起；反汇编器在share目录下的compiler目录，汇编器和宏汇编器的share部分代码，放在asm目录。

**Comment by shining1984** [comment]
可以预见的修改是src/utils/hsdis目录下的Makefile和hsdis.c。

**Comment by shining1984** [comment]
从源码编译binutils:
1、从 https://ftp.gnu.org/gnu/binutils/ 下载 binutils-2.36.1.tar.xz ；
2、xz -d binutils-2.36.1.tar.xz
3、tar xvf binutils-2.36.1.tar
4、在src/utils/hsdis目录下：mkdir build && cd build
5、将binutils-2.36.1粘贴到src/utils/hsdis/build目录下；
6、在build目录下: mkdir linux-riscv32 && cd linux-riscv32
7、在linux-riscv32目录下运行：CFLAGS = '-fPIC -O' ../binutils-2.36.1/configure --disable-nls --host=riscv32-unknown-linux-gnu
8、make

编译hsdis demo:
1、切换到src/utils/hsdis目录；
2、make demo BINUTILSDIR=build/binutils-2.36.1 ARCH=riscv32 CC=riscv32-unknown-linux-gnu-gcc
3、 /path/to/riscv/qemu/bin/qemu-riscv32 build/linux-riscv32/hsdis-demo
这个时候，执行了一半，出现了错误：
![image](https://user-images.githubusercontent.com/3916635/113962928-3f841a00-985b-11eb-86cb-313053aabda3.png)

**Comment by shining1984** [comment]
尝试使用了2.33.1、2.35、2.35.1的binutils，但是在编译binutils的时候，就报了代码错误。

咨询了陈嘉炜，binutils是从2.35开始支持rv32g的，推荐使用最新的2.36.1版本。

**Comment by shining1984** [comment]
Segmentation fault目前还没找到根源，怀疑是binutils内部的问题。

已经将目前修改提交到 #73 。验证过程如上面所写过程。

@DingliZhang ，请review和验证。

**Comment by DingliZhang** [comment]
#73 已review和验证
已合并

**Comment by DingliZhang** [comment]
FYI @shining1984 使用binutils2.37 可以顺利运行hsdis demo。

![image](https://user-images.githubusercontent.com/19571377/127015076-c0e3a9fd-cb2c-429a-be54-c6e061e04c15.png)

**Comment by shining1984** [comment]
从源码编译binutils:
1、从 https://ftp.gnu.org/gnu/binutils/ 下载 binutils-2.37.tar.xz ；
2、xz -d binutils-2.37.tar.xz
3、tar xvf binutils-2.37.tar
4、在src/utils/hsdis目录下：mkdir build && cd build
5、将binutils-2.37粘贴到src/utils/hsdis/build目录下；
6、在build目录下: mkdir linux-riscv32 && cd linux-riscv32
7、export PATH=/riscv32 toolchain dir/bin:$PATH
8、在linux-riscv32目录下运行：CFLAGS='-fPIC -O' ../binutils-2.37/configure --disable-nls --host=riscv32-unknown-linux-gnu
9、make

编译hsdis demo:
1、切换到src/utils/hsdis目录；
2、make demo BINUTILSDIR=build/binutils-2.37 ARCH=riscv32 CC=riscv32-unknown-linux-gnu-gcc
3、 /path-to-riscv-qemu/bin/qemu-riscv32 build/linux-riscv32/hsdis-demo
可以执行demo，输出成功的信息：
![image](https://user-images.githubusercontent.com/3916635/127085205-2a8eec66-ec5b-4e38-88aa-3f20681a6d3e.png)


注意：如果遇到了找不到libdl.so.2的问题，实际上通过locate libdl.so.2发现有多个不同目标平台的这个库，然后echo LD_LIBRARY_PATH，发现其为空，export LD_LIBRARY_PATH=/riscv32-toolchain-dir/sysroot/lib，因为该目录下有riscv32的libdl.so.2。然后可以解决这个问题。

**Comment by ZhangXiang1994-max** [comment]
针对找不到libdl.so.2的情况，还可以使用-L的方法解决
![image](https://user-images.githubusercontent.com/84717784/127088761-79c2f002-6303-4f0c-978b-194226db2d6a.png)

**Comment by DingliZhang** [comment]
移除了`src/utils/hsdis/hsdis.c`中重复的include，已提交 https://github.com/openjdk-riscv/jdk11u/pull/162 对当前结果不会有影响，
请 @shining1984 验证和review
