### ISSUE TITLE
复查shining在macroAssembler的提交之前的load和store指令移植

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#78]
#39 中更新了最新版本的load和store指令移植移植规则，根据该规则，重新检查之前的提交。

**Comment by shining1984** [comment]
src/hotspot/cpu/riscv32

1. templateInterpreterGenerator_riscv32.cpp
    sd->sw,ld->lw,lwu->lw,addw->add

**Comment by shining1984** [comment]
src/hotspot/cpu/riscv32/templateTable_riscv32.cpp

1.sd->sw, ld->lw, lwu->lw

**Comment by shining1984** [comment]
src/hotspot/cpu/riscv32/interpreterRT_riscv32.cpp

1. fsw->sw, flw->lw 
这等于更正了之前的ld->flw, sd->fsw；才用了ld->lw, sd->sw规则。

**Comment by shining1984** [comment]
interp_masm_riscv32.hpp and interp_masm_riscv32.cpp

fsw->sw, flw->lw
这等于更正了之前的ld->flw, sd->fsw；采用了ld->lw, sd->sw规则。

**Comment by shining1984** [comment]
jniFastGetField_riscv32.cpp

改了一个 flw->lw

**Comment by shining1984** [comment]
icBuffer_riscv32.cpp and sharedRuntime_riscv32.cpp

部分：fsw->sw, flw->lw
这等于更正了之前的ld->flw, sd->fsw；采用了ld->lw, sd->sw规则。
进行ld->flw, sd->fsw之前的fsw和flw没有更改。

**Comment by shining1984** [comment]
#79 已经提交。每个提交节点对应着之前一个patch的更新。

验证过程和结果如 #70 .

@DingliZhang 请帮忙review和验证。

**Comment by DingliZhang** [comment]
已经review并且合并。
