### ISSUE TITLE
复查dingli在Assembler的提交之前的load和store指令移植

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#81]
#39 中更新了最新版本的load和store指令移植移植规则，根据该规则，重新检查之前的提交。

**Comment by DingliZhang** [comment]
src/hotspot/cpu/riscv32/methodHandles_riscv32.cpp

部分：flw->lw
这等于更正了之前的ld->flw；采用了ld->lw规则。

**Comment by DingliZhang** [comment]
src/hotspot/cpu/riscv32/stubGenerator_riscv32.cpp
部分：flw->lw, fsw->sw
这等于更正了之前的ld->flw, sd->fsw；采用了ld->lw, sd->sw规则。

src/hotspot/cpu/riscv32/vtableStubs_riscv32.cpp
部分：flw->lw
这等于更正了之前的ld->flw；采用了ld->lw规则。

**Comment by DingliZhang** [comment]
#82 已经提交。每个提交节点对应着之前一个patch的更新。

验证过程和结果如 #70 .

@shining1984 请帮忙review和验证。

**Comment by shining1984** [comment]
已经合并。
