### ISSUE TITLE
fix issue83中暴露出来的macroAssembler的错误

### ISSUE THREAD

**Issue by shining1984** [openjdk-riscv/jdk11u#85]
使用的编译配置：

bash configure \
--with-boot-jdk=/home/dingli/jdk-10 \
--openjdk-target=riscv32-unknown-linux-gnu \
--with-sysroot=/home/dingli/toolchain/riscv32/sysroot \
--disable-warnings-as-errors \
--with-debug-level=fastdebug \
--with-native-debug-symbols=internal \
--with-jvm-variants=core \
--prefix=$PWD/fastdebug_32_core
configure 可以通过，在执行make -j时报错：

dingli@dingli-ubuntu-1804-01:~/isrc-jdk11u/jdk11u$ make -j
Building target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
Compiling 2 files for BUILD_JVMTI_TOOLS
Compiling 1 files for BUILD_JFR_TOOLS
Parsing 2 properties into enum-like class for jdk.compiler
Compiling 13 properties into resource bundles for jdk.javadoc
Compiling 12 properties into resource bundles for jdk.jdeps
Compiling 19 properties into resource bundles for jdk.compiler
Compiling 7 properties into resource bundles for jdk.jshell
Compiling 117 files for BUILD_java.compiler.interim
Creating support/modules_libs/java.base/server/libjvm.so from 695 file(s)
Creating hotspot/variant-core/libjvm/gtest/libjvm.so from 96 file(s)
Creating hotspot/variant-core/libjvm/gtest/gtestLauncher from 1 file(s)
Compiling 394 files for BUILD_jdk.compiler.interim
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:498:8: error: 'void MacroAssembler::mv(Register, int)' cannot be overloaded with 'void MacroAssembler::mv(Register, int32_t)'
  498 |   void mv(Register Rd, int imm);
      |        ^~
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:497:8: note: previous declaration 'void MacroAssembler::mv(Register, int32_t)'
  497 |   void mv(Register Rd, int32_t imm32);
      |        ^~
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp: In member function 'void MacroAssembler::cast_primitive_type(BasicType, Register)':
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:763:7: error: 'addw' was not declared in this scope; did you mean 'add'?
  763 |       addw(Rt, Rt, zr);
      |       ^~~~
      |       add
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp: In member function 'bool MacroAssembler::is_valid_riscv64_address(address)':
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:798:29: warning: right shift count >= width of type [-Wshift-count-overflow]
  798 |     return ((uintptr_t)addr >> 48) == 0;
      |             ~~~~~~~~~~~~~~~~^~~~~
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:498:8: error: 'void MacroAssembler::mv(Register, int)' cannot be overloaded with 'void MacroAssembler::mv(Register, int32_t)'
  498 |   void mv(Register Rd, int imm);
      |        ^~
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:497:8: note: previous declaration 'void MacroAssembler::mv(Register, int32_t)'
  497 |   void mv(Register Rd, int32_t imm32);
      |        ^~
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp: In member function 'void MacroAssembler::cast_primitive_type(BasicType, Register)':
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:763:7: error: 'addw' was not declared in this scope; did you mean 'add'?
  763 |       addw(Rt, Rt, zr);
      |       ^~~~
      |       add
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp: In member function 'bool MacroAssembler::is_valid_riscv64_address(address)':
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:798:29: warning: right shift count >= width of type [-Wshift-count-overflow]
  798 |     return ((uintptr_t)addr >> 48) == 0;
      |             ~~~~~~~~~~~~~~~~^~~~~
lib/CompileGtest.gmk:59: recipe for target '/home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/gtest/objs/precompiled/precompiled.hpp.gch' failed
make[3]: *** [/home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/gtest/objs/precompiled/precompiled.hpp.gch] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [/home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/precompiled/precompiled.hpp.gch] Error 1
lib/CompileJvm.gmk:151: recipe for target '/home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/precompiled/precompiled.hpp.gch' failed
make[2]: *** [hotspot-core-libs] Error 2
make[2]: *** Waiting for unfinished jobs....
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed
Compiling 299 files for BUILD_jdk.javadoc.interim

ERROR: Build failed for target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-core_libjvm_gtest_objs_precompiled_precompiled.hpp.gch:
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:498:8: error: 'void MacroAssembler::mv(Register, int)' cannot be overloaded with 'void MacroAssembler::mv(Register, int32_t)'
  498 |   void mv(Register Rd, int imm);
      |        ^~
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:497:8: note: previous declaration 'void MacroAssembler::mv(Register, int32_t)'
  497 |   void mv(Register Rd, int32_t imm32);
      |        ^~
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp: In member function 'void MacroAssembler::cast_primitive_type(BasicType, Register)':
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:763:7: error: 'addw' was not declared in this scope; did you mean 'add'?
  763 |       addw(Rt, Rt, zr);
   ... (rest of output omitted)
* For target hotspot_variant-core_libjvm_objs_precompiled_precompiled.hpp.gch:
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:498:8: error: 'void MacroAssembler::mv(Register, int)' cannot be overloaded with 'void MacroAssembler::mv(Register, int32_t)'
  498 |   void mv(Register Rd, int imm);
      |        ^~
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:497:8: note: previous declaration 'void MacroAssembler::mv(Register, int32_t)'
  497 |   void mv(Register Rd, int32_t imm32);
      |        ^~
In file included from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/asm/macroAssembler.hpp:31,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/interpreter/abstractInterpreter.hpp:28,
                 from /home/dingli/isrc-jdk11u/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:111:
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp: In member function 'void MacroAssembler::cast_primitive_type(BasicType, Register)':
/home/dingli/isrc-jdk11u/jdk11u/src/hotspot/cpu/riscv32/macroAssembler_riscv32.hpp:763:7: error: 'addw' was not declared in this scope; did you mean 'add'?
  763 |       addw(Rt, Rt, zr);
   ... (rest of output omitted)

* All command lines available in /home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-fastdebug/make-support/failure-logs.
=== End of repeated output ===

=== Make failed targets repeated here ===
lib/CompileGtest.gmk:59: recipe for target '/home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/gtest/objs/precompiled/precompiled.hpp.gch' failed
lib/CompileJvm.gmk:151: recipe for target '/home/dingli/isrc-jdk11u/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/precompiled/precompiled.hpp.gch' failed
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed
=== End of repeated output ===

Hint: Try searching the build log for the name of the first failed target.
Hint: See doc/building.html#troubleshooting for assistance.

/home/dingli/isrc-jdk11u/jdk11u/make/Init.gmk:300: recipe for target 'main' failed
make[1]: *** [main] Error 2
/home/dingli/isrc-jdk11u/jdk11u/make/Init.gmk:186: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by shining1984** [comment]
Building target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug'
Creating support/modules_libs/java.base/server/libjvm.so from 13 file(s)
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:562:6: error: no declaration matches 'void Assembler::add(Register, Register, int32_t, Register)'
  562 | void Assembler::add(Register Rd, Register Rn, int32_t increment, Register temp) {
      |      ^~~~~~~~~
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/assembler.hpp:454,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:31,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:29:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:1209:8: note: candidates are: 'void Assembler::add(Register, Register, int64_t, Register)'
 1209 |   void add(Register Rd, Register Rn, int64_t increment, Register temp = t0);
      |        ^~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:388:8: note:                 'void Assembler::add(Register, Register, Register)'
  388 |   INSN(add,   0b0110011, 0b000, 0b0000000);
      |        ^~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:377:8: note: in definition of macro 'INSN'
  377 |   void NAME(Register Rd, Register Rs1, Register Rs2) {          \
      |        ^~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:259:7: note: 'class Assembler' defined here
  259 | class Assembler : public AbstractAssembler {
      |       ^~~~~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:582:6: error: no declaration matches 'void Assembler::li(Register, int32_t)'
  582 | void Assembler::li(Register Rd, int32_t imm) {
      |      ^~~~~~~~~
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/assembler.hpp:454,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:31,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:29:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:299:8: note: candidate is: 'void Assembler::li(Register, int64_t)'
  299 |   void li(Register Rd, int64_t imm);  // optimized load immediate
      |        ^~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:259:7: note: 'class Assembler' defined here
  259 | class Assembler : public AbstractAssembler {
      |       ^~~~~~~~~
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/globalDefinitions.hpp:29,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/align.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/runtime/globals.hpp:29,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/memory/allocation.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/oops/array.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/memory/universe.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/code/oopRecorder.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/codeBuffer.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/assembler.hpp:28,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:31,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:29:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp: In member function 'void Assembler::movptr_with_offset(Register, address, int32_t&)':
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:735:35: error: 'imm64' was not declared in this scope
  735 |   assert(is_unsigned_imm_in_range(imm64, 47, 0) || (imm64 == (uintptr_t)-1), "48-bit overflow in address constant");
      |                                   ^~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/utilities/debug.hpp:55:9: note: in definition of macro 'vmassert'
   55 |   if (!(p)) {                                                                  \
      |         ^
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:735:3: note: in expansion of macro 'assert'
  735 |   assert(is_unsigned_imm_in_range(imm64, 47, 0) || (imm64 == (uintptr_t)-1), "48-bit overflow in address constant");
      |   ^~~~~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:737:17: error: 'imm64' was not declared in this scope; did you mean 'imm'?
  737 |   int32_t imm = imm64 >> 16;
      |                 ^~~~~
      |                 imm
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/assembler_riscv32.o' failed
make[3]: *** [/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/assembler_riscv32.o] Error 1
make[2]: *** [hotspot-core-libs] Error 2
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed

ERROR: Build failed for target 'default (exploded-image)' in configuration 'linux-riscv32-normal-core-fastdebug' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target hotspot_variant-core_libjvm_objs_assembler_riscv32.o:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:562:6: error: no declaration matches 'void Assembler::add(Register, Register, int32_t, Register)'
  562 | void Assembler::add(Register Rd, Register Rn, int32_t increment, Register temp) {
      |      ^~~~~~~~~
In file included from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/asm/assembler.hpp:454,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/share/precompiled/precompiled.hpp:31,
                 from /home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.cpp:29:
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:1209:8: note: candidates are: 'void Assembler::add(Register, Register, int64_t, Register)'
 1209 |   void add(Register Rd, Register Rn, int64_t increment, Register temp = t0);
      |        ^~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:388:8: note:                 'void Assembler::add(Register, Register, Register)'
  388 |   INSN(add,   0b0110011, 0b000, 0b0000000);
      |        ^~~
/home/shining/jdk-dev/shiningning/jdk11u/src/hotspot/cpu/riscv32/assembler_riscv32.hpp:377:8: note: in definition of macro 'INSN'
  377 |   void NAME(Register Rd, Register Rs1, Register Rs2) {          \
      |        ^~~~
   ... (rest of output omitted)

* All command lines available in /home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/make-support/failure-logs.
=== End of repeated output ===

=== Make failed targets repeated here ===
lib/CompileJvm.gmk:151: recipe for target '/home/shining/jdk-dev/shiningning/jdk11u/build/linux-riscv32-normal-core-fastdebug/hotspot/variant-core/libjvm/objs/assembler_riscv32.o' failed
make/Main.gmk:272: recipe for target 'hotspot-core-libs' failed
=== End of repeated output ===

Hint: Try searching the build log for the name of the first failed target.
Hint: See doc/building.html#troubleshooting for assistance.

/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:300: recipe for target 'main' failed
make[1]: *** [main] Error 2
/home/shining/jdk-dev/shiningning/jdk11u/make/Init.gmk:186: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by shining1984** [comment]
@DingliZhang 帮忙review和验证。

**Comment by DingliZhang** [comment]
已经review和验证，已合并
