### ISSUE TITLE
OpenJDK11.0.9.1-ga Zero VM SPECjvm2008 benchmark on HiFive Unleashed

### ISSUE THREAD

**Issue by DingliZhang** [openjdk-riscv/jdk11u#9]
I used https://github.com/sifive/freedom-u-sdk (2020.12.00) and apply the OpenSBI patch https://github.com/riscv/opensbi/commit/7dcb1e1753e9c5daec0580779ea8c31778bff152 which fix sign-extension in sbi_misaligned_load_handler().
Finally I run openjdk11.0.9.1-ga Zero VM SPECjvm2008 benchmark on HiFive Unleashed.

Tips: Two compiler. * cases cannot run on jdk11, so ignore them. 
Openjdk11u.log in zip archives is redirect log which run with `java -Xmx4096m -jar SPECjvm2008.jar -ikv -ict -coe  > openjdk11u.log 2>&1 &
`
Here is the results.  : )
[results_20210204.zip](https://github.com/openjdk-riscv/jdk11u/files/5923824/results_20210204.zip)

**Comment by shining1984** [comment]
测试结果已经附在issue中。
